### ISSUE TITLE
Kan inte backa tillbaks till appen från webbvy

### ISSUE THREAD

**Issue by jooon** [kolplattformen/skolplattformen#100]
När jag klickar på en av länkarna i Aviseringar hamnar jag i en webbvy som visar rätt information.

Backa-knappen i Android fungerar dock inte alls här. Det går inte att backa tillbaka till appen och det går inte att backa inne i webbvyn efter att ha följt någon länk. Det finns en rad längst upp som visar domännamn på domänen jag anlände till från appen. Klickar jag mig vidare ut på internet ändras inte domännamnet trots att jag befinner mig på en annan domän.

Det finns även en svart, rund x-ikon till höger om domännamnet som ser ut som om den skulle stänga sidan, men inget händer när jag trycker på den.

Skärmdump från aviseringslänk hos testanvändaren 121212-1212.
![Screenshot_20210213-150334](https://user-images.githubusercontent.com/13156/107852075-d5c53200-6e0e-11eb-97a7-8aa5f2251682.jpg)

Lyckades "backa" tillbaka in i en appen genom att sätta appen i split screen som tar mig tillbaka till inloggningsvyn.

App-version 1.1.1
Google Pixel 2 XL, Android 11

**Comment by JohanObrink** [comment]
Fixat i v1.3.0
