### ISSUE TITLE
Alla ikoner leder till Nyheter

### ISSUE THREAD

**Issue by jooon** [kolplattformen/skolplattformen#101]
App-version: 1.1.1
Google Pixel 2 XL, Android 11.

1. Starta appen
2. Logga in med testanvändaren 121212-1212
3. Tryck på ikonen längst till höger under det första barnet.

Förväntar mig att hamna i tabben Klassen.
Hamnar istället i tabben Nyheter.

**Comment by believer** [comment]
Tack för en utmärkt buggrapportering 😄 Jag har gjort en fix för den som mergas snart!
