### ISSUE TITLE
Texten i iPhones statusfält borde vara svart vid ljus bakgrund

### ISSUE THREAD

**Issue by zhouhana** [kolplattformen/skolplattformen#103]
Jämför:

![image](https://user-images.githubusercontent.com/493629/107853739-f5ad2380-6e17-11eb-8ac3-9ca3d998ff26.png)

och

![image](https://user-images.githubusercontent.com/493629/107853742-f8a81400-6e17-11eb-9c16-921b96e05e14.jpeg)

med

![image](https://user-images.githubusercontent.com/493629/107853744-fb0a6e00-6e17-11eb-8076-c66257a767d2.png)

**Comment by believer** [comment]
@zhouhana Jag kunde inte reproducera ditt fel exakt. Jag gissar att det var iPhone SE (första generationen) som du rapporterade i #104? Jag har iaf lagt till en grej som explicit sätter statusfältet till att använda **mörkt innehåll** så får vi se om det löser buggen 😄

**Comment by zhouhana** [comment]
Ja, nu är det löst. Tack! "Mörkt innehåll" leder mina tankar till ljus text på mörk bakgrund men du ser jag hursomhelst statusfältet som jag vill, med svart text på ljus bakgrund.

**Comment by believer** [comment]
@zhouhana ja, jag tycker också den är lite tvärtom, men det är så den funkar 😅
