### ISSUE TITLE
Namnet på mitt barn fortsätter utanför skärmen

### ISSUE THREAD

**Issue by zhouhana** [kolplattformen/skolplattformen#104]
Se bild.

![image](https://user-images.githubusercontent.com/493629/107853807-4e7cbc00-6e18-11eb-8dc1-adae38aa4eb8.jpeg)

**Comment by irony** [comment]
Tack! Vi lägger till ett namn i testdatat som är extra långt så att vi säkerställer att vi kan hantera dessa korrekt.

**Comment by JohanObrink** [comment]
@zhouhana @irony Problemet är att när jag testar det (lade till Efraimsdotter Långstrump på slutet) så radbryter den snällt. Jag antar att det har med enskilda namns längd att göra?

Skulle du kunna kommentera med ett namn med samma ungefärliga antal bokstäver utan att för den skull avslöja för mycket?

**Comment by zhouhana** [comment]
Tack!

Förnamnet består av sju bokstäver och efternamnet är ett dubbelt efternamn på nio respektive fem bokstäver och det är de två sista bokstäverna som hamnar utanför. Jag använder en första generationens iPhone SE.
