### ISSUE TITLE
Otydligt menyalternativ för notifieringar

### ISSUE THREAD

**Issue by zhouhana** [kolplattformen/skolplattformen#105]
![image](https://user-images.githubusercontent.com/493629/107853969-1cb82500-6e19-11eb-995f-1ffcf81f56d1.jpeg)

Jag skulle hellre se denna typ av symbol:

![image](https://user-images.githubusercontent.com/493629/107853974-2772ba00-6e19-11eb-8716-fa195c8f6f4a.png)

Och även gärna att det svengelska och långa ordet "notifieringar" byttes ut mot antingen "aviseringar" (som i Android) eller "notiser" (som i iOS).

**Comment by zhouhana** [comment]
Nu ser jag att det verkar ha stått "aviseringar" förut. Jag tycker dock att det är bättre än "notifieringar". Bra med så korta ord som möjligt också för att undvika grafiskt strul. "Notiser" kan dock vara förvirrande bredvid "Nyheter".

**Comment by zhouhana** [comment]
Eller, förlåt, nu inser jag ju att det inte är notifications/aviseringar det handlar om. Så en bjällra som symbol blir ju missvisande. Men vad är det då? I mitt fall består listan av ”lärloggar” från Unikum. Är det alltid ”lärloggar” det handlar om? Då kanske det är så det ska stå. Eller i värsta fall ”Unikum”.

**Comment by JohanObrink** [comment]
@zhouhana Tack för din Issue 👍🏻 

Detta är löst i v1.1.0.
