### ISSUE TITLE
UX: Move navigation to bottom

### ISSUE THREAD

**Issue by stefannilsson** [kolplattformen/skolplattformen#116]
![navi_bottom](https://user-images.githubusercontent.com/7548473/107887788-d2ae6c80-6f08-11eb-8ad4-148b77ffc10e.png)

**Comment by irony** [comment]
Jättebra poäng! InUse har erbjudit sig att göra en analys av UX och komma med rekommendationer, jag skickar med detta som en bra och enkel åtgärd.
