### ISSUE TITLE
Update readme with requirements for development environment

### ISSUE THREAD

**Issue by erickr** [kolplattformen/skolplattformen#118]
The readme is currently missing information on what is required to set up a development environment. 

The following did not give a working development version:
```
npm install
npm run-script bootstrap

```
Tested using:
npm -v: 6.14.11
node -v: 14.15.5

Tested on a debian buster.

**Comment by believer** [comment]
@erickr jag har öppnat en PR med uppdaterad dokumentation i #123 om hur att köra `app` och `site`. Kan du få igång dem med hjälp av den dokumentationen?

**Comment by erickr** [comment]
> @erickr jag har öppnat en PR med uppdaterad dokumentation i #123 om hur att köra `app` och `site`. Kan du få igång dem med hjälp av den dokumentationen?

Tyvärr inte, jag ska försöka kolla dokumentationen om jag kan få ut mer info än detta. 
```
$ npx lerna bootstrap
npx: installed 767 in 20.954s
lerna notice cli v3.22.1
lerna info Bootstrapping 2 packages
lerna info Installing external dependencies
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 2 in 'skolplattformen'
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 2 in 'skolplattformen'

```

**Comment by believer** [comment]
Härligt att `site` funkar iaf 😄 Kan du köra `yarn`/`npm install` direkt i `packages/app` och få något felmeddelande?

**Comment by erickr** [comment]
> Härligt att `site` funkar iaf  Kan du köra `yarn`/`npm install` direkt i `packages/app` och få något felmeddelande?

Haha, yes, jag verkade ha fel version android build tools bl.a. Får kolla vidare ikväll! :)Tack

**Comment by objarni** [comment]
1. clona repot
2. npm install
3. npm run test
Crash!

Upprepade kommandot "npm run test" efter varje av följande:
   npm install yarn
   npm install jest
.. men det ser fortfarande knas ut.

Saknas några dev.dependencies i package.json månne?
Förväntas man inte kunna köra 1-3 i "roten" av repot?
Var är "How to run tests"-receptet? :)

**Comment by erickr** [comment]
@objarni Se min tidigare kommentar på https://github.com/kolplattformen/skolplattformen/issues/118#issuecomment-779097245

Har du android studio installerat? Jag kom en bit längre när jag såg till att ha android studio och build tools v29. Men jag labbar mig fram lite för att inte belasta projektet mer än nödvändigt med setup-fix. :) Men dokumentation behöver bli lite bättre.
