### ISSUE TITLE
Öppna förvald mejlapp vid tryck på "Maila"

### ISSUE THREAD

**Issue by zhouhana** [kolplattformen/skolplattformen#131]
Skolplattformen vill öppna appen Mail som jag inte längre har installerad på min iPhone. Jag använder istället Gmails app och det har jag även angivit i inställningarna i iPhone (Inställningar > Gmail > Förvald app för mejl). Att kunna ange förvald app för mejl och förvald webbläsare är nytt i senaste iOS.

![default-app-1-300](https://user-images.githubusercontent.com/493629/108203022-39f33900-7122-11eb-9380-49b9c3092009.png)
![default-app-2-300](https://user-images.githubusercontent.com/493629/108203025-3b246600-7122-11eb-88b1-d9778687037a.png)

**Comment by believer** [comment]
Vi använder bara `mailto:<mailadress>` vilket borde öppna din förvalda app. Gmail kanske behöver fixa något på sin sida enligt denna? [Preparing Your App to be the Default Browser or Email Client](https://developer.apple.com/documentation/xcode/allowing_apps_and_websites_to_link_to_your_content/preparing_your_app_to_be_the_default_browser_or_email_client)

**Comment by zhouhana** [comment]
Där ser man! Just nu fungerar ju inte klasslistan men när/om den gör det igen så är det ett bra alternativ att köra som Slack gör i denna bild.

![slack-email](https://user-images.githubusercontent.com/493629/111906274-0886c980-8a50-11eb-82f6-d97a7602dc04.png)

**Comment by believer** [comment]
Tack, bra idé!

**Comment by pontusab** [comment]
Eller använd: https://github.com/flexible-agency/react-native-email-link
