### ISSUE TITLE
Minska bilderna och/eller gör om dem till bakgrundsbilder

### ISSUE THREAD

**Issue by zhouhana** [kolplattformen/skolplattformen#133]
Bilderna får inte plats helt på mindre skärmar. Dessutom påverkar de och påverkas av elementen ovanför och undertill.

Kan bilderna visas som bakgrundsbilder kanske och avståndet till texten "Öppna Skolplattformen" med tillhörande underubrik minskas?

Snyggt också om texten i bilden inte krockar med statusraden högst upp på skärmen.

Skärmdumparna är från första generationens iPhone SE.

![bilder-1](https://user-images.githubusercontent.com/493629/108203777-40ce7b80-7123-11eb-986c-8655405cbabf.png)
![bilder-2](https://user-images.githubusercontent.com/493629/108203782-41ffa880-7123-11eb-8928-ab06603c9832.png)

**Comment by believer** [comment]
@zhouhana vi har gjort en del fixar i #172 så snart borde logga in/logga ut se bättre ut för iPhone SE!

| Logga in | Logga in (med tangentbord uppe) | Logga ut | 
| ------ | ----- | ----- |
| ![Simulator Screen Shot - iPhone SE (1st gen) - 2021-02-23 at 10 08 26](https://user-images.githubusercontent.com/1478102/108822390-4f071680-75bf-11eb-8683-6596d076d792.png) | ![Simulator Screen Shot - iPhone SE (1st gen) - 2021-02-23 at 10 08 30](https://user-images.githubusercontent.com/1478102/108822393-50384380-75bf-11eb-8b35-c4b2c9a759d1.png) | ![Simulator Screen Shot - iPhone SE (1st gen) - 2021-02-23 at 10 08 39](https://user-images.githubusercontent.com/1478102/108822397-50d0da00-75bf-11eb-85b5-d3790a81c7e4.png) |

**Comment by zhouhana** [comment]
Fantastiskt bra jobbat. Appen går verkligen från klarhet till klarhet.
