### ISSUE TITLE
Nyheterna är avklippta (allt visas inte)

### ISSUE THREAD

**Issue by olaxandersson** [kolplattformen/skolplattformen#138]
Exempel:

![IMG_20210218_103147](https://user-images.githubusercontent.com/79253370/108337875-e6422780-71d5-11eb-93ee-c360a9088c2a.jpg)

Alla andra är också avklippta.

**Comment by JohanObrink** [comment]
Fixat i v1.2.0 (iOS) resp. v1.3.0 (Android)
