### ISSUE TITLE
Någon slags encodingproblem i nyheter

### ISSUE THREAD

**Issue by mansj** [kolplattformen/skolplattformen#147]
Det här är i en nyhet från vår skola. Som synes är det inget problem med encodingen till att börja med, men sen blir det konstigt när de har klistrat in text från annan källa. 

Det ser bra och normalt ut i ”stängda Skolplattformen”

Jag är på iPad, iOS 14.3

![1A4E1328-7B3B-4D7D-8DE1-F9D76EE0C630](https://user-images.githubusercontent.com/592768/108471521-cec57600-728b-11eb-8ed2-c98ebabb52c2.png)

**Comment by kajetan-kazimierczak** [comment]
Är du på senaste versionen av appen? Jag hade liknande fel där den verkade tappa bort sig efter en länk, men det löste sig med en uppdatering för ett par dagar sen.

**Comment by mansj** [comment]
Nej, det verkar helt klart vara löst om jag testar i 1.2.0 via Testflight. Sorry.
