### ISSUE TITLE
Se vistelsetid

### ISSUE THREAD

**Issue by zhouhana** [kolplattformen/skolplattformen#154]
Jag vet inte om det är olika för grundskolan och förskolan, men i Stängda Skolplattformen kan man se sitt förskolebarns vistelsetid genom att gå till Vistelsetid > Tillfällig ändring. Det logiska hade varit att istället kunna se vistelsetiden under Vistelsetid > Visa schema, men där ser man istället alla schemalager ett och ett, även utgångna scheman, och måste klicka på vart och ett för att veta vilket eller vilka som är aktuella. Lagren verkar fungera som CSS beroende på när de las in och vad de har för start- och slutdatum, och det är bara under "Tillfällig ändring" som de är hopslagna. Detta har jag rapporterat till staden för 1,5 år sedan sen. Jag vet inte om det finns något färdig värde för det hopslagna schemat att hämta eller om Öppna skolplattformen måste tillämpa samma hopslagningsregler för att få samma resultat. I det senare fallet behöver man kolla noggrannt hur de olika lagren påverkar varandra i Stängda Skolplattformen så att man gör likadant.

**Comment by irony** [comment]
Vi skulle behöva utvecklare som har barn i förskolan för just nu kan vi inte se hur dessa strukturer ser ut och kan därför inte komma vidare utan dokumentation. Här finns det ett jättebra tillfälle för fler utvecklare att hjälpa till!

**Comment by zhouhana** [comment]
Jag förstår. Jag hjälper gärna till men kan tyvärr inte programmera (och har tyvärr inte heller så mycket tid). Om ni behöver att jag kollar upp något via min inloggning så hjälper jag gärna till om jag får instruktioner. Har två barn i förskolan varav ett börjar förskoleklass i höst.

**Comment by dubbelnisse** [comment]
@irony har finns de barn och en utvecklare! Vad vill ni ha hjälp med?

**Comment by believer** [comment]
@dubbelnisse välkommen! 😄 jag tänker att det vore bra att börja med att få igång appen lokalt och testa om du kan se något som inte fungerar för dig med förskolebarn? Jag kan fixa en "Förskola" label där vi vet att det handlar om det så kanske du kan plocka någon av dem sen?
