### ISSUE TITLE
Klasskompisar försvann (funkade vid start)

### ISSUE THREAD

**Issue by piaullstrom** [kolplattformen/skolplattformen#159]
Plötsligt tom lista, för ett par dagar sedan syntes de som godkänt. Förskola. Kan inte jmf med skolplattformen för där får får jag bara tekniskt fel idag :)
![895A5A6A-0D1F-4D9E-A5C2-1D20BCE354F8](https://user-images.githubusercontent.com/78951134/108530585-06591000-72d6-11eb-8622-3f51b1fb877b.jpeg)

**Comment by kajetan-kazimierczak** [comment]
I samband med detta står det nu felaktigt "Förskoleklass" som klass för mitt barn. Gissar att appen inte kan hitta barnets klass. Var hittar man ens klasslistan på den "riktiga" skolplattformen?

**Comment by zhouhana** [comment]
Samma här. Tom klasslista och nu står det bara "FS" under barnens namn istället för som förut förskolans avdelning.

**Comment by kajetan-kazimierczak** [comment]
Jag har kollat nu och Skolplattformen returnerar en tom lista på klasskompisar (och även en tom lista på lärare) så de visas inte på kontaktsidan i Skolplattformen heller just nu. Inte för mitt barn i alla fall. Så felet ligger hos Stockholm.

**Comment by believer** [comment]
Detta är en bugg i Skolplattformen! [Här är mer information om buggen](https://twitter.com/oppnaskolplatt/status/1363287341566148610?s=19)
