### ISSUE TITLE
Understrykning i nyheter fungerar inte, och whitespace runt om klipps bort

### ISSUE THREAD

**Issue by EmilStenstrom** [kolplattformen/skolplattformen#160]
Understrykning i nyheter fungerar inte, och whitespace runt om klipps bort. Sen det gulmarkerade i bilden nedan. På webben är samma del understruken, så jag gissar att det är en <u>-tagg som behöver lägga till i en lista av godkända taggar...?

<img width="414" alt="Screenshot 2021-02-19 at 18 47 31" src="https://user-images.githubusercontent.com/224130/108541855-4246a200-72e3-11eb-8b6a-c16a7ae6bbee.png">

**Comment by kajetan-kazimierczak** [comment]
Fixat i 1.9.4

**Comment by EmilStenstrom** [comment]
Tack! ❤️
