### ISSUE TITLE
Klassen

### ISSUE THREAD

**Issue by norly1** [kolplattformen/skolplattformen#161]
Klasslistan visar inga kontakter. Har barn på Enskedeskolan. 

![Skärmavbild 2021-02-20 kl  05 26 27](https://user-images.githubusercontent.com/79348724/108583828-a6e21b00-733c-11eb-9797-3514fca8977a.jpeg)

**Comment by irony** [comment]
Tack! Kan du dubbelkolla om det finns elever när du går in i den officiella skolplattformen och klickar på Kontakt? Vårdnadshavare behöver nämligen godkänna att deras personuppgifter får publiceras och har ni inte gjort det så kan det vara ett bra tips att maila vårdnadshavare att gå in och godkänna?

**Comment by irony** [comment]
Vi lägger in en instruktion som förklarar detta lite tydligare: 
<img width="371" alt="image" src="https://user-images.githubusercontent.com/395843/108610175-d2fcab00-73d3-11eb-9718-e8a9dc90f243.png">
