### ISSUE TITLE
bug: Dina barn Laddar... och mobilt bank id login

### ISSUE THREAD

**Issue by andaqui** [kolplattformen/skolplattformen#174]
Kom till sidan Dina barn och står bara och "Laddar...". 
(Har två barn som syns i vanliga skolplattformen.)

Sedan verkar login med mobilt bank id buggat, antingen extremt segt och/eller hänger sig ibland. Olika fallen:
1. Hänger sig på "väntar på BankID" och mobilt bank id appen öppnas inte. Går manuellt till mobilt bank id och certifiering är igång. Certifierar och går tillbaka till appen och står ändå bara "Väntar på bankId"
2. Hänger sig på "väntar på BankID" och mobilt bank id appen öppnas inte. Går manuellt till mobilt bank id så finns ingen certifiering igång.
3. Mobilt bank id appen öppnas från skol-appen, man loggar in och klickar på "skolplattformen" tillbaka ios textknapp uppe till vänster, kommer till appen som skickar en tillbaka till mobilt bank id återigen. 

Lyckades logga in en gång och fick då Laddar problemet.

Använder:
iPhone 11 Pro
iOs 14.4

Hoppas det går att lösa, vanliga skolplattformen är katastrofal.

**Comment by andaqui** [comment]
Nu när jag testar någon timme senare så lirar det med både login och Dina barn.

**Comment by believer** [comment]
@andaqui inloggningen kanske kan ha varit någonting relaterat till [BankID låg nere under attack](https://www.svt.se/nyheter/inrikes/bank-id-ligger-nere-1)? 🤔

**Comment by ErikHellman** [comment]
Tack för felrapporten. Vi stänger den här då just det här problemet inte verkar relevant längre. :)
