### ISSUE TITLE
Står bara och laddar efter inloggning

### ISSUE THREAD

**Issue by andersjaensson** [kolplattformen/skolplattformen#178]
Efter inloggning kommer man inte vidare. Står bara "Laddar..."

Eventuellt relaterat till det här?

https://www.dn.se/sthlm/stockholm-stoppar-alternativa-appen-for-skolplattformen/

**Comment by ErikHellman** [comment]
Det stämmer att det är relaterat till den ändringen. Vi har en fix på det hela och håller på att testa den nu. 

Vi kommer meddela via vårt Twitter konto när vi har en färdig lösning på väg ut till alla användare. :)

https://twitter.com/oppnaskolplatt

**Comment by believer** [comment]
Just detta felet har fixats, sen har Stockholms stad gjort nya ändringar som förstört, men just detta borde vara fixat!
