### ISSUE TITLE
Stor text gör att man inte kommer vidare

### ISSUE THREAD

**Issue by jonaspalm** [kolplattformen/skolplattformen#179]
När telefonen är inställd (iPhone) på större text (under hjälpmedel) så kommer man inte vidare i appen. Texten tränger undan knapparna så att de inte syns.

**Comment by jonaspalm** [comment]
![DD9B0043-AD41-4FA8-9550-B695296A725B](https://user-images.githubusercontent.com/79729212/109368225-bad7d080-7898-11eb-8320-154093a9a466.jpeg)

**Comment by irony** [comment]
Tack! Det här ska vi titta på och åtgärda.

**Comment by believer** [comment]
I den senaste versionen så tror jag att detta kan vara löst. Jag har bara tillgång till iPhone simulatorn, men där fungerar det just nu bra i två modeller `iPhone 11` och `iPhone SE` (som är den minsta skärmstorleken vi stödjer). Där ligger knapparna i botten av skärmen. Vi har även tagit bort texten "Hurra..." och justerat storleken på personnumret.

@jonaspalm kvarstår problemet även i den senaste versionen?

| iPhone SE | iPhone 11 |
| ------ | ----- |
| ![Simulator Screen Shot - iPhone SE (1st gen) - 2021-03-04 at 16 30 09](https://user-images.githubusercontent.com/1478102/109987761-32798580-7d07-11eb-850f-814e95bb20c7.png) | ![Simulator Screen Shot - iPhone 11 - 2021-03-04 at 16 28 00](https://user-images.githubusercontent.com/1478102/109987766-33aab280-7d07-11eb-8cb6-e0bc1bffeec4.png) |

**Comment by believer** [comment]
Den här sidan finns inte kvar, användaren kommer direkt till listan med barn istället och logga ut ligger på ett annat ställe. https://github.com/kolplattformen/skolplattformen/pull/206
