### ISSUE TITLE
Logga ut automatiskt efter viss tid

### ISSUE THREAD

**Issue by zhouhana** [kolplattformen/skolplattformen#196]
De flesta appar som har BankID-inloggning loggar ut användaren efter 5–20 minuters inaktivitet, och det känns säkert och bra tycker jag. Slutna Skolplattformen verkar dock INTE göra det – innebär det att det är tekniskt omöjligt för Öppna Skolplattformen att göra det? Om inte skulle detta kunna vara en möjlighet att slå staden på fingrarna säkerhetsmässigt.

**Comment by kajetan-kazimierczak** [comment]
Själva inloggningen gäller bara ett tag så man blir i praktiken utloggad ändå (även i slutna skolplattformen skulle jag tro), men det borde synas i appen på något sätt. Nu kan man fortsätta använda appen och läsa alla nyheter som man redan laddat ner, men man får inte uppdateringarna och kanske inte fattar att man måste logga ut och in igen.

**Comment by zhouhana** [comment]
Ja, det är förvirrande, och själva säkerhetsaspekten går förlorad.

**Comment by ptz0n** [comment]
Varför inte behålla inloggningen så länge sessionen tillåter, och istället låsa appen lokalt? Låses upp med exempelvis Touch- eller FaceID?

**Comment by kajetan-kazimierczak** [comment]
Man skulle kunna, varje gång man kommer tillbaka till appen, kolla https://etjanst.stockholm.se/Vardnadshavare/base/getuserdata för att se om man fortfarande är inloggad.
