### ISSUE TITLE
Bilderna i nyhetslistan

### ISSUE THREAD

**Issue by zhouhana** [kolplattformen/skolplattformen#198]
Det verkar svårt att få till bilderna i nyhetslistan. Antingen är de för stora eller så tränger de in rubrikerna så att de måste löpa över fyra, fem rader.

![image](https://user-images.githubusercontent.com/493629/111912145-a4243400-8a68-11eb-840a-7dfa22694e30.jpeg)

Kanske vi inte behöver bilder alls i nyhetsflödet, utan bara inne på själva nyheterna?

Annars är ett alternativ att lägga bilden som bakgrund under rubriken med skuggning under texten för ökad kontrast. Se exempel från MSN.com. Då kan man både ha bilder och långa rader utan att det påverkar nyhetslistans längd så mycket.

![image](https://user-images.githubusercontent.com/493629/111912155-aedec900-8a68-11eb-883c-657e0a009e0a.jpeg)

**Comment by kajetan-kazimierczak** [comment]
Bilderna är viktiga tycker jag, om skolan använder de vettigt och inte har samma bild för alla inlägg. Däremot kan man kanske skippa första orden i ingressen och bara visa rubrik och datum.

**Comment by zhouhana** [comment]
Ja, just i mina listor tillför inte ingressen något; jag skulle nog inte sakna dem.

Håller också med om att bilder är trevligt men jag tycker att det är minst lika viktigt att rubrikerna inte trängs in i ett hörn. I nuläget ryms inte ens långa ord på en rad, och får märklig radbrytning. Misstänker att det är svårt att rätta till på annat sätt än att ge orden mer utrymme.

![image](https://user-images.githubusercontent.com/493629/111944320-ab365b00-8ad7-11eb-9c9a-5f3d3515206f.jpeg)

![image](https://user-images.githubusercontent.com/493629/111944332-b1c4d280-8ad7-11eb-96bc-ba732ccbdb49.jpeg)

**Comment by kajetan-kazimierczak** [comment]
"Min" skola sätter väldigt korta rubriker (typ ofta bara datum "20-03-17" osv) och det enda jag kan använda som någon sorts ankarpunkt för att veta vad som är vad är illustrationerna och ingressen. Så det är lite tveeggat svärd detta. ;) 
Det är dessutom beroende på storleken på telefonen. På min iPhone 11 ser det inte alls så smalt ut som på dina bilder. Kanske finns det något sätt att minska marginalerna på telefoner med lägre upplösning?

**Comment by zhouhana** [comment]
Ah, då förstår jag att det är viktigt för dig. Jag använder en iPhone SE från 2016 med skärm på 4". Det verkar som att de flesta mobilmodeller som lanserats efter 2016 har åtminstone något större skärm än så, så vi som klamrar oss fast vid en gammal modell kanske får tåla att det ser ut som det gör, helt enkelt. (Men jag tycker fortfarande att mitt alternativa förslag är intressant.)

**Comment by believer** [comment]
Vi skulle kunna ta bort bilden helt från listan i mindre enheter? Om det är något viktigt i bilden så finns den ju inne på nyheten.

**Comment by zhouhana** [comment]
Ja, det låter som en bra mellanväg tycker jag.
