### ISSUE TITLE
Påminnelse om frånvaroanmälan

### ISSUE THREAD

**Issue by zhouhana** [kolplattformen/skolplattformen#202]
När ett barn frånvaroanmälts genom Öppna appen vore det snyggt om det nästa dag gick ut en pushnotis med en fråga om barn X ska frånvaroanmälas även den dagen.

Åtminstone i förskolan är det viktigt för planeringen att frånvaroanmälan görs dagligen innan 7.30, och jag vet att det varit jättestruligt med detta under de värsta smittovågorna det senaste året. Folk glömmer, speciellt sjukdag två och framåt. Man kanske kommer på det klockan 8.00 men då är dagens planering redan lagd.

Om Öppna appen genom en sådan påminnelse kunde öka antalet frånvaroanmälningar som görs i tid skulle det underlätta för personalen. Då skulle även personalen – inte bara föräldrarna – få en anledning att förespråka appen.

Kanske är tiden 7.10 lämplig för den här pushnotisen. Om den kommer vid 7.00 är det risk att den tävlar med väckarklockan om uppmärksamheten, och om den kommer innan 7.00 är det risk att man tänker att man har god tid på sig innan 7.30 och sedan glömmer ändå.

Eventuellt skulle man när man frånvaroanmäler kunna kryssa i en ruta om man vill ha påminnelse nästa dag och eventuellt då även kunna ändra den föreslagna tiden.

(Jag föreslog detta för staden i november och de skulle ta det vidare, men jag misstänker att de inte tar tid att implementera det.)

**Comment by irony** [comment]
Jättebra idé! Är det någon som vet om man kan skicka pushnotiser till sig sin egen app utan att ha en server? Vi har ju ingen server nämligen av säkerhetsskäl.

**Comment by EmilStenstrom** [comment]
@irony Det verkar heta Local notification när det egentligen styrs av en timer, och fungera såhär: https://stackoverflow.com/questions/6047117/how-to-create-local-notifications

**Comment by zhouhana** [comment]
Ett tillägg som jag kom på nu efter en helg med sjuka barn: Om man sjukanmäler på en fredag vill man ha påminnelsen på måndagen, inte på lördagen. Men det kanske inte går att fixa så enkelt.

**Comment by irony** [comment]
Låter görbart! Låt oss göra ett försök.
