### ISSUE TITLE
Vyn Dina barn laddar inte i senaste versionen (1.5.5)

### ISSUE THREAD

**Issue by zhouhana** [kolplattformen/skolplattformen#204]
I version 1.5.4 fungerade det för mig men uppenbarligen inte för vissa andra. Nu i 1.5.5. fungerar det inte för mig. iPhone SE 2016.

**Comment by EmilStenstrom** [comment]
Det har att göra med att Stockholms stad har sabbat appen igen. Dom gör små ändringar i syfte att ”störa ut” appen. Riktigt uselt agerat om ni frågar mig. Utbildningsnämnden är rätt instans att kontakta.

**Comment by zhouhana** [comment]
Ja, tyvärr är det ju så. Nu efter senaste uppdateringen fungerar det igen på min mobil – vi får se hur länge till.

**Comment by believer** [comment]
Verkar fungera än så länge i `1.5.7`. Vi håller tummarna 😄
