### ISSUE TITLE
Konvertera radbrytning till mellanrum i ingress

### ISSUE THREAD

**Issue by zhouhana** [kolplattformen/skolplattformen#224]
Wow, appen blir bara mer och mer proffsig och snygg!

Nu när jag inte längre störs av inträngda rubriker i nyhetslistan hittade jag en annan grej. Vet inte om den ligger inom ÖS:s kontroll men det skulle bli ännu trevligare för ögat om radbrytningar i nyheter konverterades till mellanslag i ingressen i nyhetslistan istället för att bara tas bort.

Nyheten i exemplet visar för övrigt en problematik som uppstått på förskolor när dels ingen fattar att det finns en klasslista att godkänna sig i och dels covid gör att man inte får gå in i hallen och lägga inbjudningskort på barns hyllor. Jag vet själv två tillfällen då barn inte blivit bjudna på kalas på grund av att kalasbarnets föräldrar inte vetat hur de ska kontakta de andra barnens föräldrar.

![image](https://user-images.githubusercontent.com/493629/112951318-824b4100-913b-11eb-8759-dc8ecace8c43.jpeg)
![image](https://user-images.githubusercontent.com/493629/112951330-85dec800-913b-11eb-86b4-2b4ec7b743cc.jpeg)

**Comment by believer** [comment]
Jag har gjort en fix här https://github.com/kolplattformen/embedded-api/pull/99 som lägger till mellanslag om det saknas efter ett komma, punkt eller utropstecken 😄

**Comment by whyer** [comment]
Den här fixen är med i version 1.7.0!
