### ISSUE TITLE
Samma nyhet visas på båda barnen

### ISSUE THREAD

**Issue by sweadde** [kolplattformen/skolplattformen#246]
Version 1.6.0 på Android. Jag hade även detta problem i tidigare versionen:

Samma lista av nyheter visas för båda mina barn.

**Comment by whyer** [comment]
Den här buggen med samma nyheter för båda barnen är fixat sedan 18 mars. Eventuellt har du gammal data cachad i appen. Jag stänger den här buggrapporten, om problemet återkommer så hör av dig igen.

**Comment by sweadde** [comment]
Kan bekräfta att efter omstart av mobil så fungerar nyheterna som de ska för båda barnen. Fantastiskt.
