### ISSUE TITLE
Inte senaste nyheterna i listan

### ISSUE THREAD

**Issue by sweadde** [kolplattformen/skolplattformen#247]
Version 1.6.0 på Android.

Jag ser inte de senaste nyheterna (jämfört med vad jag ser i officiella skolplattformen som jag tyvärr tvingades logga in i).

Senaste nyheterna i öppna är från 24/2. I stadens app finns det för detta barnet 9 senare inlägg.

**Comment by sweadde** [comment]
Jag räknade fel.  Det är 9 inlägg i stadens app sen 24/3 och många många sen den 24/2.

**Comment by kajetan-kazimierczak** [comment]
Listan borde uppdateras korrekt i nästa version. Den buggen är fixad, hade med datumformat att göra.

**Comment by sweadde** [comment]
Det verkar fungera nu. Stänger denna.
