### ISSUE TITLE
Möjlighet att bläddra mellan matseldar

### ISSUE THREAD

**Issue by zhouhana** [kolplattformen/skolplattformen#257]
Det är bra för historik och planering att kunna se andra veckors matsedlar. Slutna Skolplattformen har denna funktion.

![Screenshot 2021-04-05 at 10 25 50](https://user-images.githubusercontent.com/493629/113554585-d356ab80-95f9-11eb-969d-4c588a0e6f89.png)

Jag kan inte heller testa den nya matsedelsfunktionen eftersom det inte råkar ligga något matsedel just nu under påsklovet. :)

**Comment by whyer** [comment]
Tack för synpunkten!

Vi arbetar med det vi får. Slutna plattformen har inte mindre än 4 olika sätt att hantera menyer:
1. Sharepoint-lista (vilket är alternativet du har ovan) har menyer för massor av veckor bakåt men endast fram till och med aktuell vecka. Vi kan inte få fram nästa veckas meny (tex på söndag kväll)
2. RSS - har får vi endast aktuell vecka. Har inte lyckats luska ut om man kan skicka in något smart till anropet för att får annan data. Slutna plattformen har ingen sådan funktion.
3. Google Calendar - tydligen används detta av vissa skolor. Inget vi stödjer då ingen utvecklare i teamet har en skola med denna funktionen
4. Iframe - man tar matsedeln från ett externt system. Här har vi ingen kontroll. Men en utvecklare i teamet har en skola med denna lösning så det kan kanske dyka upp

Vi skulle kunna implementera bläddring bakåt på alternativ 1 ovan. 

Vi är lite låsta av staden här. Vill man ha mer funktioner får jag peka mot https://www.skolmaten.se/

**Comment by zhouhana** [comment]
Ah, det är ju just framåt man vill kunna bläddra när man ska planera veckan, men att kunna bläddra bakåt kan också vara trevligt. Många kök lägger kanske inte in menyn i förväg heller. Så alternativ 1 är det bästa i nuläget tycker jag det känns som.

Mina barns förskola har för övrigt inte anslutit sig till https://www.skolmaten.se/ Jag ska fråga om de kan göra det. Dock gillar jag inte att info om skolgång och dylikt delas upp i pyttebitar på olika privata lösningar och hoppas inte att ÖS gör sig beroende av sådana.

**Comment by whyer** [comment]
Jag var otydligt ser jag nu. Vi kan alltså inte välja alternativ. Vissa skolor kör alternativ  1, andra alternativ 2 osv. Det beror helt enkelt på barn. 

Då staden inte kapslat in de olika alternativen bakom ett gemensamt api, måste alla klienter (dvs både Slutna Plattformen och vi) stödja alla 4 alternativen. Det är urbota dumt gjort.

**Comment by zhouhana** [comment]
Ah, jag förstår. Tråkigt. 

Som sagt är inte alla förskolor och skolor anslutna till Skolmaten.se, och det kostar tydligen att ansluta sig.

Det bästa är kanske att låta det vara som det är och att eventuellt lägga till något i stil med "för att se andra veckors matsedlar hänvisar vi till Skolmaten.se" och/eller en förklaring, eller en länk till en förklaring, om varför det är tekniskt omöjligt att själva erbjuda detta. Tillägget är inte nödvändigt såklart men jag kan tänka mig att fler än jag kommer att fundera över varför de inte kan se andra matsedlar än den innevarande veckans.
