### ISSUE TITLE
Byt namn på alla förekomster av "meny"/"Meny" till "Matsedel" och ta bort "Veckans"

### ISSUE THREAD

**Issue by zhouhana** [kolplattformen/skolplattformen#258]
"Meny" dels eftersom det antyder att man kan välja mellan olika alternativ, vilket inte alltid är fallet, och dels eftersom Slutna Skolplattformen kallar det "Matsedel". Inte för att SS alltid har så bra namn på saker och ting ("Aviseringar" – suck!) men där de faktiskt har det är det bra att vara konsekvent.

"Veckans" dels eftersom "Veckans meny" inte får plats på mindre skärmar,  och dels eftersom jag hoppas att man i framtiden kommer kunna bläddra mellan veckornas matsedel precis som i Slutna Skolplattformen (se #257), och då blir "Veckans" missvisande.

![2021-04-05 10 10 16](https://user-images.githubusercontent.com/493629/113554336-74913200-95f9-11eb-9370-74ed2a3754bd.jpg)

**Comment by whyer** [comment]
Mycket bra! Namnändring fixas till nästa release.
Bläddring är lite mer komplicerat. Se svar i #257
