### ISSUE TITLE
Nyhetsbilder utan titel/bildtext får felmeddelande

### ISSUE THREAD

**Issue by zhouhana** [kolplattformen/skolplattformen#261]
Se jämförelse mellan ÖS och SS.

![image](https://user-images.githubusercontent.com/493629/113663014-83372200-96a9-11eb-8e1a-bca52f8ac43e.png)

![image](https://user-images.githubusercontent.com/493629/113663027-892d0300-96a9-11eb-8b1b-00a82573801c.png)

**Comment by irony** [comment]
Tack!

**Comment by kajetan-kazimierczak** [comment]
Jag har en fix på g. för detta i embedded-api. Borde komma med i nästa version.
