### ISSUE TITLE
Möjlighet att backa tillbaka från Unikum

### ISSUE THREAD

**Issue by zhouhana** [kolplattformen/skolplattformen#262]
När man följt en länk till Unikum kan man inte backa tillbaka till ÖS.

![2021-04-06 05 50 15](https://user-images.githubusercontent.com/493629/113706179-ab8d4380-96de-11eb-9fee-ce5d750fee25.png)

SS har en backpil i sin app som syns på alla sidor men just från Unikum klarar inte heller den av att backa.

![2021-04-06 06 12 12](https://user-images.githubusercontent.com/493629/113706199-b34ce800-96de-11eb-9c3c-8685e77f82f2.png)

Facebook och Twitter har löst samma problem så här. Facebooks lösning, där webbläsaren inte täcker hela appfönstret, känns användarvänlig tycker jag men Twitters, som känns enklare och påminner om SS' lösning, känns också helt okej.

![2021-04-06 09 23 55](https://user-images.githubusercontent.com/493629/113706408-f0b17580-96de-11eb-8262-8cad96f2b73b.png)

![2021-04-06 09 25 03](https://user-images.githubusercontent.com/493629/113706440-f909b080-96de-11eb-813c-619481f6fc3a.png)

**Comment by whyer** [comment]
Man kan backa men det är otydligt... tryck på "krysset" uppe i högra hörnet.

**Comment by irony** [comment]
Håller med om att krysset är svårt att hitta. Jag gillar överlappet med kryss som finns på FB

**Comment by zhouhana** [comment]
Ja, jag trodde att det krysset var för att rensa adressfältet. Dölj gärna hela adressfältet där tycker jag, så som Facebook och övriga gjort.
