### ISSUE TITLE
Lägga till fler kommuner?

### ISSUE THREAD

**Issue by Leverpastej** [kolplattformen/skolplattformen#278]
Hej,

Jag är ny här så detta kanske redan har tagits upp samt att jag har inte hittat något svar på min fundering/förbättringsförslag:
Men är det möjligt att få in fler kommuner är Stockholm Stad? Alla använder (tyvärr) Schoolsoft så vitt jag vet (?) så det borde fungera kanske?

**Comment by irony** [comment]
Det här vore toppen! Helsingborg har hört av sig, Alingsås också. Börja gärna genom att kolla med dessa tekniskt och skriv gärna här i tråden vad ni hittar. Tekniskt sett så är det enklaste om man gör en kopia av embedded_api och döper den till alingsas_api eller schoolsoft_api och sedan gör adaptrar för dessa. Detta lib är vältestat och när väl alla tester går igenom för en ny kommun så ska i teorin appen fungera precis som vanligt fast med två kommuner istället för en.

**Comment by Leverpastej** [comment]
Vad kul att många är så intresserade! Precis och då kan man välja vilken kommun man bor i så vet appen vilken API den ska använda istället för att kolla mot alla kommuner.

Jag är tyvärr ingen utvecklare fast jag kan lite PowerShell och PowerApp + Power Bi kodning så jag vet inte hur mycket jag kan hjälpa till men jag stöttar i det jag kan.

Var hittar jag "embedded_api"?

**Comment by rawtaz** [comment]
@Leverpastej Sannolikt här: https://github.com/kolplattformen/embedded-api

**Comment by twogood** [comment]
Schoolsofts app är i stort sett en webview med JSP-sidor som rendreras på deras servrar. Så det finns inte ens ett API.
