### ISSUE TITLE
Implement a platform for crowdsourced translation

### ISSUE THREAD

**Issue by axdra** [kolplattformen/skolplattformen#299]
Implement a platform like [Weblate](https://weblate.org/) to the project, for easier translation of the app for non programmers. 

This would improve language support and also improve the quality of the translations, but also minimize the hassle for non programmers to help with translation.

Because I feel like translation is a important feature and also hard to solve if we need to find developers that know "all" languages.

This also improves workflow, Weblate for example has git integration so it's very seamless. 

Weblate could be self-hosted to reduce cost on using this service for example.

**Comment by whyer** [comment]
This is a very good suggestion and we are currently looking into it.

**Comment by viktorlarsson** [comment]
... Great suggestion! it's now up and running

https://hosted.weblate.org/engage/skolplattformen/

**Comment by axdra** [comment]
Saw that! Awesome!
