### ISSUE TITLE
Använd en pull-down menu istället för ActionSheet på iOS 14+

### ISSUE THREAD

**Issue by edenstrom** [kolplattformen/skolplattformen#313]
Hej,

För lite finare upplevelse för t.ex. funktionerna "Välj inloggningsmetod" och kugghjulet för logga ut, skulle vi kunna använda en [Pull-down menu](https://developer.apple.com/design/human-interface-guidelines/ios/controls/pull-down-menus/) istället för ett [ActionSheet](https://developer.apple.com/design/human-interface-guidelines/ios/views/action-sheets/).

Citerat från actionsheet-dokumentationen:
> Use an action sheet to request confirmation before performing a potentially destructive operation. To give people a choice of items or actions that are related to a nondestructive task, you can use a pull-down menu.

Support är endast iOS 14+, men vi får lägga till en fallback till ActionSheet via [`Platform`](https://reactnative.dev/docs/platform).

Modulen [react-native-ios-context-menu](https://github.com/dominicstop/react-native-ios-context-menu) går att använda. Har tidigare använt den i ett annat app-projekt.

Har inga barn i Stockholm, men öppen att jobba på en PR om idén låter bra.

Screenshots:
<img width="369" alt="CleanShot 2021-04-21 at 21 36 50@2x" src="https://user-images.githubusercontent.com/4541038/115610865-b86a8380-a2e9-11eb-8228-0e811bb18ef9.png">
ActionSheet

<img width="520" alt="CleanShot 2021-04-21 at 21 36 42@2x" src="https://user-images.githubusercontent.com/4541038/115610878-bb657400-a2e9-11eb-8afc-570de0361ead.png">
Pull-down menu

**Comment by whyer** [comment]
Tycker det låter som en bra idé! PR låter fantastiskt.
Du kan logga in som testanvändare, då ser du två test-barn med testdata. Det borde fungera bra för utveckling.

**Comment by edenstrom** [comment]
Bra feedback @whyer. Kikar på det. :) 

Jag börjar nog med en snabb mockup och skapar en issue/postar en kommentar för hur det skulle kunna se ut.

Såg issue #367 också som kan vara relaterad.

Finns det någon Slack/Discord eller liknande för såna här typer av diskussioner, eller är det github issues som gäller?
