### ISSUE TITLE
Skriv appens namn konsekvent

### ISSUE THREAD

**Issue by zhouhana** [kolplattformen/skolplattformen#333]
I AppStore heter appen "Öppna Skolplattformen" med versalt S. På sajten och i själva appen förekommer gement s.

Om man tolkar Skolplattformen som ett egennamn så ska det förstås vara versalt S. Jämför om en app skulle heta "Öppna facebook".

Om det är så att tanken istället är att andra kommuner ska kunna använda exakt samma app för sina egna tekniska lösningar, och att skolplattformen alltså inte ska tolkas som ett egennamn här, så bör det skrivas med gement s även i AppStore och på eventuella andra ställen där det står med versalt S.

Synka namnet i sociala medie-konton, på Discord/Slack, t-shirts, formella dokument osv.

**Comment by comradekingu** [comment]
Svenska sättet att skriva på är "Öppna skolplattformen", då undviker man också att utge seg for att vara själva "Skolplattformen".

Jag gillar "Öppna skolplattformen" som ackusativ-verb ~Ni måste öppna.

**Comment by comradekingu** [comment]
Neverstale

**Comment by zhouhana** [comment]
Jag tänkte i början att Skolplattformen med versalt S kändes bäst eftersom det var en direkt reaktion på Skolplattformen, men nu när debatten lagt sig och det kanske mer handlar om att faktiskt sträcka ut en hand åt staden (denna administration eller nästa), och kanske i första hand få andra kommuner att använda appen, så håller jag med comradekingu här ovan. Gement s känns mindre begränsande och mer neutralt – sticker inte någon i ögonen på samma sätt. Nu har vi pekat finger en stund; dags att harkla sig och räta på slipsen. 🙂

**Comment by irony** [comment]
Tack för jättebra reflektioner. Jag håller med om att det inte är självklart. Jag hoppas att Stockholm Stad börjar vilja samarbeta igen snart och då kan dessa diskussioner hamna i en strategisk diskussion tillsammans med övriga kommuner. Vi har haft diskussioner med andra kommuner som är intresserade av att samarbeta med oss. Tillsammans med övriga plattformsutvecklare hoppas jag att vi kan få till ett öppet samarbete som gör att föräldrar inte behöver leta runt i olika appar utan kan använda ett sånt här öppet alternativ istället som har adaptrar för de system den ska fungera för. Tekniskt finns det bra förutsättningar för detta så det är vad jag hoppas mest på. Vi avvaktar därmed hur det utvecklar sig med staden. 

Admentum är intressant - de äger nämligen varumärket Skolplattformen hos PRV men Stockholm Stad har överklagat den registreringen då de tycker att Skolplattform är ett för allmängiltigt koncept för att man ska kunna registrera det som varumärke. Därmed gör staden fel när de själva använder sig av Skolplattformen (med versalt S) - då det i så fall skulle betyda att de implicit begår varumärkesintrång då de språkligt använder namnet som ett egennamn. Vi har fått tillåtelse av Admentum att använda oss av deras varumärke så vi får faktiskt använda Skolplattformen med stort S.
