### ISSUE TITLE
Pushnotis med dagens matsedel

### ISSUE THREAD

**Issue by zhouhana** [kolplattformen/skolplattformen#344]
En frivillig pushnotis med dagens matsedel, är det tekniskt möjligt? Matsedeln är det som jag som förskoleförälder gärna har koll på från dag till dag.

(Relaterad tanke: Kan tänka mig att skolföräldrar gärna skulle kunna välja att på eftermiddag/tidig kväll få en pushnotis med morgondagens läxa också – ja, notiser om allt sånt som man som god förälder annars skulle behöva logga in dagligen för att kolla. Att slippa logga in regelbundet skulle vara en fin selling point för ÖS. Men jag har ingen aning om hur läxor och annat skolrelaterat visas upp i systemet; om det bara är typ fritext i veckobrev blir det ju svårt att göra en notis av det.)

**Comment by irony** [comment]
Ja när lärare börjar skriva in läxor på ett mer standardiserat sätt skulle det vara toppen att kunna lägga in dem som pushnotiser men tyvärr är det än så länge bara i veckobrev som lärare verkar skriva in dessa som fritext. Vi har faktiskt försökt tyda ut dem med hjälp av AI men inte ens då kan vi få ut alla. Man skriver datum på så olika sätt.
