### ISSUE TITLE
Tydligare kontrast på aktiv tabb?

### ISSUE THREAD

**Issue by irony** [kolplattformen/skolplattformen#356]
![image](https://user-images.githubusercontent.com/395843/116921952-fbffae80-ac54-11eb-846a-c0c3a679302a.png)

**Comment by irony** [comment]
Jag tolkar detta som att vi borde testa att göra strecket ovanför aktiv tabb med högre kontrast. Tex svart eller mörkare röd/blå?

**Comment by webberian** [comment]
Ja precis, det är så det ska tolkas.
