### ISSUE TITLE
Översätt åtkomst till kalender

### ISSUE THREAD

**Issue by irony** [kolplattformen/skolplattformen#358]
![image](https://user-images.githubusercontent.com/395843/116922201-4f71fc80-ac55-11eb-9f6a-c6a5e27ca662.png)

**Comment by comradekingu** [comment]
Den finns av någon anledning här
https://github.com/kolplattformen/skolplattformen/blob/e4b39a70b4e648c9cf14092da04ac7c2808e131a/packages/app/ios/app/Info.plist#L52
