### ISSUE TITLE
Kalendervyn: nästan omöjligt att skrolla hela vägen ner

### ISSUE THREAD

**Issue by webberian** [kolplattformen/skolplattformen#365]
I kalendern på iOS finns för testbarnet Shanel en lång lista med händelser. Listan hoppar dock hela tiden tillbaka till början vid skrollning, och man måste hålla listan på plats för att försöka komma hela vägen ner. 
Bugg?

**Comment by kajetan-kazimierczak** [comment]
När schema visas så verkar listan med kalenderhändelser åka ner utanför skärmen med motsvarande höjd. Då blir den svår eller omöjlig att scrolla i, beroende på antalet händelser i listan och typ av device.
