### ISSUE TITLE
Kalenderhändelser croppas (Android)

### ISSUE THREAD

**Issue by rotsee** [kolplattformen/skolplattformen#377]
Kalenderhändelser med långa namn eller beskrivningar ryms inte i vyn på Android. Önskemål: Antingen göra kalendervyn större (och scrollande) när det behövs, eller göra det möjligt att expandera en händelse genom att klicka på den
 
![image](https://user-images.githubusercontent.com/122874/117576297-aa887100-b0e5-11eb-9460-8bbf93129205.png)

**Comment by kajetan-kazimierczak** [comment]
Blir så även på iPhone. Vi klurar på lösning. 
Min egna lösning just nu är att vända telefonen 90 grader så får allt plats :)

**Comment by rotsee** [comment]
> Blir så även på iPhone. Vi klurar på lösning.
> Min egna lösning just nu är att vända telefonen 90 grader så får allt plats :)

Den lösningen räcker bara fram till lunch på min telefon... :) de senare lektionerna hamnar utanför boxen, och går inte att scrolla sig till

**Comment by irony** [comment]
Vi ska ge kalendern mer plats genom att flytta summeringen av dagen till startsidan istället. Sedan kommer vi använda ett custom typsnitt vilket gör att det kommer se likadant ut på Android och iOS. Förhoppningsvis löser den här sig automatiskt då. Tack för att du rapporterade!

**Comment by kajetan-kazimierczak** [comment]
Kalenderhändelserna fick nyligen mer plats, så jag stänger denna
