### ISSUE TITLE
Visa pdf i app

### ISSUE THREAD

**Issue by superture** [kolplattformen/skolplattformen#394]
En av mina barns skolor skickar veckobrev etc i PDF. Vore super om de kunde visas i appen på android istället för att laddas ner som fil.

Keep up the good work ✌️

**Comment by comradekingu** [comment]
@superture

Ni kan ladda ner
https://f-droid.org/en/packages/com.artifex.mupdf.mini.app/ (lite)
eller https://f-droid.org/en/packages/org.koreader.launcher/ (stort) och öppna i ett utav dom programmen.

I Android finns en MIME-info tagg som kan ta reda på om det finns stöd for et filformat. Det vore bättre att skicka länk till et program om det inte finns, och heller öppna med den intentionen.
När man så öppnar en fil frän et annat program (här ifrån Öppna skolplattformen) kan man gå tillbaks (från PDF-programmet) efteråt och så komma in i originalprogrammet, utan att byta mellan programmen själva.

PDF är et skrotformat med säkerhetsfel vänster och höger. Att implementera stöd som del av själva programmet är (i bäste fall) inte tillrådligt.

Fråga om dom kan skicka i TXT (om det inte finns bilder), eller ODF/ODT.
