### ISSUE TITLE
Automatisera skärmdumpar

### ISSUE THREAD

**Issue by edenstrom** [kolplattformen/skolplattformen#403]
Just nu är det spridda skurar på skärmdumpar, både på webben och i app store/google play. Många är inaktuella.

Vi skulle automatisera dessa med hjälp av [Fastlane](https://fastlane.tools/) och [Detox](https://github.com/wix/Detox).

Då kan vi också få in:
- Screenshots i både Dark mode/Light mode.
- Screenshots på flera olika språk
- Screenshots på flera olika enheter

**Comment by comradekingu** [comment]
@edenstrom Dom används i https://hosted.weblate.org/screenshots/skolplattformen/app-translation/ som kontext till textsträngar också.

Det är rätt enkelt att söka upp något där och förklara med bild när någon ställer frågar.
