### ISSUE TITLE
Toppnavigeringen dålig på Android.

### ISSUE THREAD

**Issue by kajetan-kazimierczak** [kolplattformen/skolplattformen#439]
Efter designuppdatering: Toppnavigeringen beter sig mycket annorlunda på Android än på iOS. Endast titeln syns, ingen animering när man scrollar bort, osv.

**Comment by viktorlarsson** [comment]
Lite osäker vad problemet här är, sitter på emulator på Pixel 3

**Comment by kajetan-kazimierczak** [comment]
Det är ok nu, jag stänger denna
