### ISSUE TITLE
"underrubriken" på inloggningssidan för långt ifrån appens namn

### ISSUE THREAD

**Issue by kajetan-kazimierczak** [kolplattformen/skolplattformen#440]
Före designändringen ligger underrubriken direkt under appens namn, som en kaxig statement.

![simulator_screenshot_E1BC7ABA-B276-41F9-97F8-4A4701ADFAC3](https://user-images.githubusercontent.com/5851132/129699222-55642ccc-0c07-442a-a080-e1eafa8ec182.png) 

Efter ändringen ligger den under knappen och ser inte ut att höra till "Öppna skolplattformen" på samma sätt som innan.

![simulator_screenshot_21770F29-535C-4985-87BB-6A9AE94F34D5](https://user-images.githubusercontent.com/5851132/129698952-62937dd3-e9b2-4a37-b388-bb8de9d9a4cd.png)

**Comment by edenstrom** [comment]
Håller med. Vi flyttar upp den under och vänsterjusterar. Eventuellt får vi ändra lite på textstilen, men det ser vi efter flytten.

**Comment by kajetan-kazimierczak** [comment]
Jag vill minnas att den fanns där förut, men flyttades ner pga inloggningsknappen åkte utanför bild i vissa fall (när inmatningsfältet för personnummer syns, tror jag). 

Så vi borde kolla på hur den sidan beter sig som helhet. Allt borde t.ex. åka upp (inte ner) när fler kontroller visas, .
Borde också testas på iPhone SE (1st gen) att det funkar med den skärmstorleken, RTL-språk, android, osv.

**Comment by viktorlarsson** [comment]
Tror jag löste detta, tittat på en pixel 3 förvisso bara

![image](https://user-images.githubusercontent.com/722315/131631112-cb7f5f4b-d33a-46ba-9fe6-2a8b3430c0e8.png)
