### ISSUE TITLE
Ta tillbaka klasslistan

### ISSUE THREAD

**Issue by kajetan-kazimierczak** [kolplattformen/skolplattformen#441]
Nu när polisanmälan är nerlagd och det kan anses bevisat på alla sätt att appen inte stjäl några uppgifter, kan det vara läge att lyfta tillbaka klasslistan? Eller är det för tidigt?

**Comment by irony** [comment]
Jag håller med. Det är dags nu. Vi borde nog aldrig tagit bort den.
