### ISSUE TITLE
Namn (och kontaktuppgifter) till lärare i lektionsschemat

### ISSUE THREAD

**Issue by kajetan-kazimierczak** [kolplattformen/skolplattformen#442]
I schemat står namnet på läraren förkortat till tre bokstäver. Det verkar i alla fall jag sett vara första bokstaven i förnamnet och två första i efternamnet.

Kontaktuppgifter till elevens lärare kan hämtas på https://etjanst.stockholm.se/vardnadshavare/inloggad2/Contacts/GetTeachersByStudent?studentId=<student-id-GUID>&schoolForm=<skolform (t.ex. GR)>

Därefter skulle man kunna försöka matcha om det finns lärare i listan som passar initialerna och skriva ut hela namnet i så fall. 
Då det är lite plats i alla små rutorna i schemat skulle man kunna öppna en större ruta om man klickar på en lektion och där även ha kontaktuppgifterna till läraren.

**Comment by irony** [comment]
Bra idé!
