### ISSUE TITLE
Ge åtkomst till barn via ombud

### ISSUE THREAD

**Issue by ChristianSternudd83** [kolplattformen/skolplattformen#444]
Förslag på feature:

Vår familj har två bonus-föräldrar som precis som "riktiga" föräldrar engagerar sig i barnens skolgång.
Dessa bonusföräldrar har såklart inte åtkomst till barnen i skolplattformen då de inte är vårdnadshavare.

Men det borde enkelt gå att utforma ett juridiskt avtal där jag som vårdnadshavare ger rätten att se mitt barns information till en annan myndig person så denna då även kan se barnets data i öppna skolplattformen.

Vår familj saknar programmeringskunskap men besitter juridisk kunskap och kan således åtminstone hjälpa till med utformningen av avtalet som ingås av vårdnadshavaren som ger sitt tillstånd.

**Comment by kajetan-kazimierczak** [comment]
Det där måste du ta med de ansvariga för Skolplattformen. Öppna skolplattformens användare kan bara komma åt den information de har rätt till i Skolplattformen. Vilken information det är har inte vi någon kontroll över.

**Comment by ChristianSternudd83** [comment]
Rackarns! Jag som tänkte vi kunde komma runt den byråkratiska flaskhalsen genom att den som har rätt ger även sin rätt :)
Men jag förstår problematiken om man går direkt mot nu när du säger det.

**Comment by kajetan-kazimierczak** [comment]
Som appen fungerar rätt praktiskt (lite förenklat) är att:
1. Logga in med bank id och därifrån få en "nyckel"
2. Anropa Skolplattformen med denna nyckel och säga "ge mig en lista på mina barn". 

Det man får tillbaka bestäms av Skolplattformen. Appen i din telefon kommunicerar krypterat direkt med Skolplattformen och vi har ingen möjlighet att se eller påverka vad som skickas däremellan.

**Comment by viktorlarsson** [comment]
Stänger denna då vi kommer ha lite knepigt att lösa detta
