### ISSUE TITLE
Sparad information försvinner vid utloggning

### ISSUE THREAD

**Issue by kajetan-kazimierczak** [kolplattformen/skolplattformen#445]
När man aktivt loggar ut rensas all data i appen. Detta användes till en början till att rensa alla cachade personuppgifter men fler uppgifter har lagts till med tiden och vissa av dem ska överleva utloggning. Ex. på data som borde överleva en utloggning är:

1. Barnens personnummer som man själv lagt in för att smidigt anmäla frånvaro i appen
2. Val av språk i appen

Lämpligt borde vi se över vilka data vi sparar med flit och lägga dem på ett separat ställe som vi inte rensar vid utloggning.

**Comment by viktorlarsson** [comment]
Logout sköts i embedded-api, den rensar hela storage. Något @JohanObrink kan kika på?
