### ISSUE TITLE
Ny inloggning kan inte ladda sidan

### ISSUE THREAD

**Issue by tinafernandes** [kolplattformen/skolplattformen#453]
Just laddat ner appen men får felmeddelandet att sidan inte kan laddas vid login. iPhone 11pro

**Comment by viktorlarsson** [comment]
Vi har upptäckt ett problem efter att Stockholm Stad har gjort förändringar på sin sida. Vi undersöker det!

**Comment by whyer** [comment]
Ny version släpptes ikväll! 2.0.0 med ny design och fixar alla problem med login!
