### ISSUE TITLE
bug: 🐛 Kalender

### ISSUE THREAD

**Issue by JohanObrink** [kolplattformen/skolplattformen#46]
När jag klickar på kalenderfliken för ena barnet hamnar jag i nyhetsflödet. Kalendern är tom för båda. Och det tog ett tag att förstå hur jag skulle ta mig tillbaka in i appen från unikum.

https://appstoreconnect.apple.com/apps/1543853468/testflight/screenshots/AIJBjjk8sxO2S-pWe1Lpf0c?preReleaseVersionId=f3428a42-d1c6-477a-a22f-b10564953ffd&sort=-timestamp

**Comment by viktorlarsson** [comment]
Hur är status här @JohanObrink ?
