### ISSUE TITLE
Det går inte att välja språk

### ISSUE THREAD

**Issue by linus-aldehag** [kolplattformen/skolplattformen#465]
I den senaste version på Android går det bara att se listan på språk, inte att markera något i listan eller trycka på spara.

Testat på en Samsung Galaxy S21 Ultra med Android 11. (Testat att stoppa hårt, rensa cache etc.)

**Comment by kajetan-kazimierczak** [comment]
Fix på G https://github.com/kolplattformen/skolplattformen/pull/467
