### ISSUE TITLE
Lägg till pull-to-refresh till listor

### ISSUE THREAD

**Issue by edenstrom** [kolplattformen/skolplattformen#484]
Vi bör lägga in pull-to-refresh till listor.

Går att använda inbyggda i React Native. 

https://reactnative.dev/docs/flatlist#onrefresh
https://reactnative.dev/docs/flatlist#refreshing

UI Kittens `List` använder sig av `FlatList`.

Validera att allt ser OK ut på Android och iOS.

Eventuellt om det behövs: Lägg till en minimum-tid spinnern måste vara active innan den försvinner. Detta så att användaren märker att det faktiskt laddade data.

**Comment by whyer** [comment]
Det här är nästan samma sak, men med mer info: #66
