### ISSUE TITLE
[Suggestion] Enable/disable fullmarkt permission

### ISSUE THREAD

**Issue by alexiamcdonald** [kolplattformen/skolplattformen#491]
Currently, the biggest problem I've encounter with the skolplatform is if you are a parent with sole custody and the other parent who doesn't have custody of your child the parent with no custody can not see any information at all on the skolplatform. It's a long and stupid process which could easily be solved with a fullmarkt permission on the parent with sole custody.

This would allow for grandparents, step parents etc to also have access to the school platform.

I haven't looked into the code yet for how you would get the information for the child but if we could create a system to allow/disallow permission based fullmakt for different parent types with different permissions on settings they are allowed to look at based on the Main parents wishes.

**Comment by kajetan-kazimierczak** [comment]
Hi,

This isn't something we can fix. We don't have access to the permissions nor the information in Skolplattformen. We are only providing a front end to the data that Skolplattformen provides. What you see in Öppna skolplattformen is what the real Skolplattformen lets you see. We can't change that.

**Comment by alexiamcdonald** [comment]
Yeah I just saw this [video Demo av hur Chrome använder Skolplattformens API](https://youtu.be/EaWx3Kp7xu4) and realised that the endpoint nor the permissions are accessible. Thanks for the response.
