### ISSUE TITLE
Better subject names

### ISSUE THREAD

**Issue by webberian** [kolplattformen/skolplattformen#507]
Here are some improvement suggestions for English translations of Swedish subjects in the Calendar:

- Social studies (instead of currently "Social study subjects")
- Science (instead of currently "Science studies"); alternatively "Natural sciences"
- Physical education & health (a bit shorter than the current "Physical education and health")

**Comment by edenstrom** [comment]
Om man vill ha det kortare kanske "Phys Ed. & Health" är ok. Vad tror du?

**Comment by kajetan-kazimierczak** [comment]
Translations should be done in [weblate](https://hosted.weblate.org/projects/skolplattformen/curriculum/) 
Closing
