### ISSUE TITLE
Bilder i Nyheter skals/klipps.

### ISSUE THREAD

**Issue by Uttiponken** [kolplattformen/skolplattformen#520]
Bilder som skickas i en nyhet beter sig olika beroende på mobilenhet/ upplösning. Öppnar samma nyhet på min iPad mini respektive iphone11. På plattan är bilderna sträckta och skalade (crop), vilket resulterar i att bara mittendelen syns. Beteendet liknar #377 

IPad exempel
![EAF41258-43CF-49A1-8E7A-3A88F4582DC2](https://user-images.githubusercontent.com/28275910/140641727-1ec5e7c8-0f36-41b8-bc9c-8f2643267d4d.jpeg)

**Comment by kajetan-kazimierczak** [comment]
Bilderna har bredd satt till 100% och minsta höjd satt till 300. Dock bir de av någon anledning alltid 300px höga även om de ofta borde varit högre. Någon med inskt i hur react native renderar saker får gärna kika på det.

**Comment by edenstrom** [comment]
Tror det går att fixa med denna: https://reactnative.dev/docs/image#resizemode
