### ISSUE TITLE
Kraschar när jag trycker på barnets namn

### ISSUE THREAD

**Issue by fraxen** [kolplattformen/skolplattformen#525]
Hej - jag har två barn i samma skola. När jag trycker på det yngre barnets information funkar det ok, då kommer jag till nyheter m.m. - men för det äldre barnet så dör appen direkt utan något meddelande. I oöppna skolplattformen funkar det utan problem (eller webbgränssnittet).

Appen är 2.0.3 (20298)
Telefonen är en OnePlus 7T med Android 11 (security update 2021-10-01)

Bidrar gärna med mer information, men är inte säker på hur man kan få ut det!

**Comment by kajetan-kazimierczak** [comment]
Tack för info.

Skulle du snabbt kunna kolla hur många veckobrev det finns i Skolplattformen för varje barn?

**Comment by fraxen** [comment]
Det äldre hade 52 nyheter totalt, det yngre 83 stycken. Vet inte om det är relevant att titta på antalet veckobrev specifikt?

**Comment by majakk** [comment]
Har samma problem. (v2.0.3 build 20298)
![Screenshot_20211112-113154](https://user-images.githubusercontent.com/1549645/141453536-e5d76b2a-8dc1-43e9-889d-60c6bef4741f.png)

**Comment by fraxen** [comment]
@majakk hur får du ut en sån log?

**Comment by majakk** [comment]
@fraxen Rutan som dyker upp vid krasch (öppna skolplattformen has stopped) --> send feedback --> preview --> event log

**Comment by fraxen** [comment]
@majakk aha - jag får inte ens en sån ruta, appen bara dör (försvinner) utan någon form av meddelande - så det är möjligt att vi har hittat olika buggar.

**Comment by majakk** [comment]
Hmmm, vill minnas att man kanske måste ha developer mode påslaget - googla "android enable developer mode" för hur man gör detta.

**Comment by kajetan-kazimierczak** [comment]
> Den äldre hade 52 nyheter totalt, det yngre 83 stycken. Vet inte om det är relevant att titta på antalet veckobrev specifikt?

Vi hade fått nyss om precis detta "String length exceeds limit" i NewsList några dagar innan. Eftersom vi inte kunde komma på vad det var för sträng vi har som är för lång så gissade vi at det kan ha något att göra med konverteringen av nyhetslistan från json. Men kanske inte.

Eftersom vi bara kan se våra egna barns data och ingen av oss har råkat ut för felet så är det svårt för oss att felsöka. (Vi har inte heller någon logging påslagen i appen i nuläget för att inte råka logga någons personuppgifter).

Om någon av er är villig/har möjlighet att felsöka så gör gärna det. Alternativt om någon vill logga in på datorn och skicka oss innehållet i länken https://etjanst.stockholm.se/vardnadshavare/inloggad2/News/GetNewsArchive?bannerImageLimit=5000&childId=<child id här> för det barnet det kraschar för (det är bara nyhetsbrev så borde inte vara personuppgifter i) . 
Exakta länken med parametrar kan hittas om man går till https://etjanst.stockholm.se/Vardnadshavare/inloggad2/Nyheter och kollar i developer tools->Network

**Comment by majakk** [comment]
Tack @kajetan-kazimierczak, gjorde en liten undersökning och hittade ett par nyhetsbrev med lite större Body: på 15246 samt 18722 tecken. Min tanke är att den senare går över någon teckengräns, t.ex 16384...? Kollade även om Header: eller något annat såg konstigt ut, men inget som stack ut. Hela json-filen blev 676KB för 78 nyhetsartiklar.

**Comment by kajetan-kazimierczak** [comment]
Tack!

Jag tror jag är något på spåren.
Jag har testat med långa Body-texter och långa preamble-texter (upp till c:a 40k tecken) men det funkade (i emulatorn), blev bara segt. Men... utan body small det med samma fel. Kan ni ha nyheter med body: null eller '' i era resultat? 

Det verkar dock smälla på något totalt orelaterat inne i någon react-component, så jag får se hur vi kan lösa detta.

**Comment by majakk** [comment]
Ja det stämmer faktiskt - en av nyheterna har en Body: som faktiskt är helt utan värde (!)

**Comment by kajetan-kazimierczak** [comment]
Fix kommer i nästa version

**Comment by majakk** [comment]
⭐ Efter senaste uppdateringen så funkade det, tack! ⭐

**Comment by majakk** [comment]
Löste detta även ditt problem @fraxen ? (Om inte så har jag ju i princip kapat din buggrapport och vi får lägga upp en ny tråd där vi reder ut denna)

**Comment by kajetan-kazimierczak** [comment]
Jag kan återöppna denna om det inte är löst. 
Vill bara påpeka att man måste vara beta-testare för att ha fått den fixade versionen.  
Men det var ett tag sen vi gjorde release, så säkert snart dags för en.

**Comment by fraxen** [comment]
Nu har jag installerat betan, och det är inte löst, samma problem kvarstår, och jag får ingen buggrapport, jag har "developer mode" - appen bara dör.

**Comment by fraxen** [comment]
```
Om någon av er är villig/har möjlighet att felsöka så gör gärna det. Alternativt om någon vill logga in på datorn och skicka oss innehållet i länken https://etjanst.stockholm.se/vardnadshavare/inloggad2/News/GetNewsArchive?bannerImageLimit=5000&childId=<child id här> för det barnet det kraschar för (det är bara nyhetsbrev så borde inte vara personuppgifter i) .
Exakta länken med parametrar kan hittas om man går till https://etjanst.stockholm.se/Vardnadshavare/inloggad2/Nyheter och kollar i developer tools->Network i Chrome
```
Jag har fixat ett sådant utdrag, hur skall jag skicka det @kajetan-kazimierczak ?

**Comment by kajetan-kazimierczak** [comment]
@fraxen Vad har du för version av appen installerad nu? Jag ska kolla upp ett sätt att skicka informationen och återkommer hur du ska göra

**Comment by kajetan-kazimierczak** [comment]
@fraxen du kan maila filerna till dev@skolplattformen.org så kommer jag få dem.

Versionen som har fixen är 2.0.4 (20337) och senare.

**Comment by fraxen** [comment]
Jag har 2.0.4 (20339), och nu funkade det, så nu kan den stängas!
