### ISSUE TITLE
Not clear whose personnummer to put in “anmäl frånvaro”

### ISSUE THREAD

**Issue by kristoh** [kolplattformen/skolplattformen#526]
You just see “Personnummer”.
I’m logged in, I have picked this option on the given child. So now whose personnummer do I type in the box, mine or the child’s? It is not necessarily obvious :)

**Comment by kajetan-kazimierczak** [comment]
True. 
The fix should go into translations on weblate for all languages.

**Comment by kajetan-kazimierczak** [comment]
We now use the general.socialSecurityNumber translation for the text. We should create a new one. I can look into it next week.
