### ISSUE TITLE
Hela bilder visas inte. 

### ISSUE THREAD

**Issue by perrra** [kolplattformen/skolplattformen#554]
Bilder som är avlånga "croppas" så man inte ser hela bilden. (här under "Nyheter")

![227894DE-10A1-4288-90EE-D1B0958F41D1_1_201_a](https://user-images.githubusercontent.com/27786391/143226107-75cabe98-9349-401a-9729-c850879a317d.jpeg)

vs.

![E38B97A7-0F19-4DDC-BB7A-AC0A64B34493_1_102_o](https://user-images.githubusercontent.com/27786391/143226599-c67d0a32-3711-42a1-848e-4a9bafb689ac.jpeg)

**Comment by edenstrom** [comment]
Hej. Tack för din buggrapport. Kan du kika i senaste versionen som kom ut för någon dag sen om det löste problemet?

**Comment by perrra** [comment]
> Hej. Tack för din buggrapport. Kan du kika i senaste versionen som kom ut för någon dag sen om det löste problemet?

Nu fungerar det, tack 👍
