### ISSUE TITLE
Walk me through building the app and making a first simple contribution to the project

### ISSUE THREAD

**Issue by zhouhana** [kolplattformen/skolplattformen#565]
I tried to follow the instructions in the readme, but got stuck. Please help me out and let's improve the instructions for everyone along the way. Note that I'm still on macOS Mojave since one of my most used apps unfortunately isn't compatible with x64 versions of macOS.

So, first I ran this command:

`sudo apt install git npm`

Here I was prompted for my password. After filling that in, I got this output:

`No Java runtime present, requesting install.`

![Screenshot 2021-11-30 at 15 06 45](https://user-images.githubusercontent.com/493629/144062018-5196205a-9bc8-4db6-b9bf-29a3f513ad18.png)

Followed by this popup:

![Screenshot 2021-11-30 at 14 58 47](https://user-images.githubusercontent.com/493629/144062055-666d571b-69e3-4d9f-a257-38574849e63b.png)

So I clicked _More Info…_ and was taken to https://www.oracle.com/java/technologies/downloads/ Here I could choose between different versions of Java. I had no idea which one to pick but picked the one named _x64 DMG Installer_. After that one was downloaded, I opened it and double-clicked the icon labelled _JDK 17.0.1.pkg_.

![Screenshot 2021-11-30 at 15 11 28](https://user-images.githubusercontent.com/493629/144062897-9c660c3e-1179-42d3-9c73-e7b0ad2076aa.png)

After having walked through the installation of the JDK, I tried running `sudo apt install git npm` again but this time got this error:

`Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home/bin/apt" (-1)`

![Screenshot 2021-11-30 at 15 14 08](https://user-images.githubusercontent.com/493629/144063506-a64f944a-041b-4d21-838e-a9f01dbfb16b.png)

So right now I'm stuck there. Help me out please.

**Comment by viktorlarsson** [comment]
I will go through the installation instructions tonight when the kids are asleep!

**Comment by believer** [comment]
Awesome that you want to contribute!

`apt` is more of a Linux thing as far as I know. You can install Node (which contains `npm`) by downloading an installer from [Node.js](https://nodejs.org/en/). We are currently using Node `v14.15.4` for the app.

You can then [install Git](https://git-scm.com/downloads) using its installer.

If you are more comfortable using the terminal I would recommend installing [Homebrew](https://brew.sh/) and using it to install `git` and `node`, eg. `brew install node`.

When you got both setup you should hopefully be able to follow our instructions. Or @viktorlarsson might find something else missing tonight.

Welcome, looking forward to that first contribution 😃

**Comment by viktorlarsson** [comment]
I have now updated the developer documentation, could you please follow the instructions for your operating system and the app you would like to run and see if it's understandable?

https://github.com/kolplattformen/skolplattformen#getting-started-with-development

**Comment by viktorlarsson** [comment]
Would also advise you to pull the latest changes from main using `git pull origin main`
