### ISSUE TITLE
No message text when you have no kids in Stockholm

### ISSUE THREAD

**Issue by viktorlarsson** [kolplattformen/skolplattformen#571]
![A75BE51E-9E0A-447D-B77E-07435CC63219](https://user-images.githubusercontent.com/722315/144238285-9793f4a5-fedc-44f4-883a-03e083b53f65.png)
![B60F3FD3-F51D-4368-9165-1F164DA50B72](https://user-images.githubusercontent.com/722315/144238301-6613f6b0-d061-45d6-aaa6-0778696e276d.png)

**Comment by kajetan-kazimierczak** [comment]
White text on white background in dark mode? We should make the picture background transparent. @irony ?

**Comment by whyer** [comment]
Vi har samma bild för tom matsedel. Så du är nog bara en bakgrundsfärg som ska ändras. 

![image](https://user-images.githubusercontent.com/858620/144709197-e62f4790-b6a1-4a22-865f-4945f4487a62.jpeg)
