### ISSUE TITLE
Hjärntorget - Ability to register absence for several days ahead

### ISSUE THREAD

**Issue by marioleed** [kolplattformen/skolplattformen#575]
It would be nice if one could report absence for at least 3 days ahead. Especially now with the pandemic and recommendations that kids should stay at home for at least 2 days after their first healthy day.

With PING PONG app today one is limited to reporting today's and tomorrow's date only.

**Comment by irony** [comment]
Hjärntorget integrationen fungerar inte längre- vi behöver mer hjälp från er som är programmerare och har barn i Göteborg för att få stöd för Vklass. Skicka PM så kommer ni åt vår Discord där vi har diskussioner om hur det ska kunna gå till.
