### ISSUE TITLE
Hjärntorget - wrong lesson sorting

### ISSUE THREAD

**Issue by oskargotte** [kolplattformen/skolplattformen#590]
On the Android app, the lessons in the calendar view and the daily summary of the child card are not sorted chronologically. The sort order seems to be random. 
A quick look into the code gave me the impression that the lessons perhaps should be sorted by _startTime_ and not _startDate_.

![Screenshot_20211206-220711_ppna Skolplattformen](https://user-images.githubusercontent.com/24395233/145201398-499410eb-fafe-4fd5-9dd2-38510c72b60f.jpg)

**Comment by kajetan-kazimierczak** [comment]
Det här verkar vara mer än bara sortering eftersom vissa lektioner är dubblerade. En del kanske fixas om jag får till #591 men annars får någon Göteborgsförälder gärna ta en titt

**Comment by oskargotte** [comment]
Jag har pratat med @viktorlarsson om den här. Vet inte om han har hunnit kika på det redan. Dubbletterna är ju skumt men jag har bara sett det en dag. Sorteringen är dock alltid fel.

**Comment by kajetan-kazimierczak** [comment]
Sorteringen har jag nu fixat med #595
