### ISSUE TITLE
Hjärntorget - wrong ending time

### ISSUE THREAD

**Issue by oskargotte** [kolplattformen/skolplattformen#591]
The ending time displayed on the child card is not correct on the Android app.
In the example below there are in fact lesson ending later than 10.20.
However, this might be to the incorrect sorting of lessons, see [#590](https://github.com/kolplattformen/skolplattformen/issues/590) 

![Screenshot_20211208-121509_ppna Skolplattformen~2](https://user-images.githubusercontent.com/24395233/145202195-1fe9b84d-5604-4f71-8407-bc2416ef3555.jpg)
![Screenshot_20211208-121540_ppna Skolplattformen](https://user-images.githubusercontent.com/24395233/145202251-ed24716c-9917-4eb9-83fa-997d4fe28f38.jpg)

**Comment by kajetan-kazimierczak** [comment]
Konstigt beteende här har jag lyckats återskapa med fakeData. Jag kan kika på den.

**Comment by PhyxDevel** [comment]
The lessons are sorted on date and not timeStart.
`  const lessons = weekLessons
    .filter((lesson) => lesson.dayOfWeek === currentDate.isoWeekday())
    .sort((a, b) => a.timeStart.localeCompare(b.timeStart))`
in _daySummary.component.tsx_ will solve it.

**Comment by PhyxDevel** [comment]
Also if there are overlapping lessons at the end of the day the end date should be calculated by the last endTime and not just the last lesson endTime:
`  const endTime = lessons
    .sort((a, b) => a.timeEnd.localeCompare(b.timeEnd))[lessons.length - 1]
    .timeEnd.slice(0, 5)`
I can make a pr later tonight

**Comment by oskargotte** [comment]
> The lessons are sorted on date and not timeStart. ` const lessons = weekLessons .filter((lesson) => lesson.dayOfWeek === currentDate.isoWeekday()) .sort((a, b) => a.timeStart.localeCompare(b.timeStart))` in _daySummary.component.tsx_ will solve it.

Yes that's what I thought as well. And the same fix should go into _week.component.tsx_ I guess?

**Comment by kajetan-kazimierczak** [comment]
> I can make a pr later tonight

I can fix it. Already started
