### ISSUE TITLE
Schemat visar kommande vecka, men förra veckans lunch under helgen

### ISSUE THREAD

**Issue by kajetan-kazimierczak** [kolplattformen/skolplattformen#599]
Schemat byter till nästa vecka under helgen vilket är bra.

I schemat ser man lunch. Eftersom lunch för nästa vecka inte finns i skolplattformen (inte för alla i alla fall) så borde man kanske gömma maträtterna i schemat när det är helg?

**Comment by whyer** [comment]
Vi gör precis detta för framsidan men glömde schemat.
