### ISSUE TITLE
Visa schema 

### ISSUE THREAD

**Issue by irony** [kolplattformen/skolplattformen#75]
Rapporterat från twitter: 
https://twitter.com/krhalas/status/1360119241433874432?s=21

**Comment by zhouhana** [comment]
+1 på denna!

Jag vet inte om det är olika för grundskolan och förskolan, men i Stängda Skolplattformen kan man se sitt förskolebarns vistelsetid genom att gå till Vistelsetid > Tillfällig ändring. Det logiska hade varit att istället kunna se vistelsetiden under Vistelsetid > Visa schema, men där ser man istället alla schemalager ett och ett, även utgångna scheman, och måste klicka på vart och ett för att veta vilket eller vilka som är aktuella. Lagren verkar fungera som CSS beroende på när de las in och vad de har för start- och slutdatum, och det är bara under "Tillfällig ändring" som de är hopslagna. Detta har jag rapporterat till staden för 1,5 år sedan sen. Jag vet inte om det finns något färdig värde för det hopslagna schemat att hämta eller om Öppna skolplattformen måste tillämpa samma hopslagningsregler för att få samma resultat. I det senare fallet behöver man kolla noggrannt hur de olika lagren påverkar varandra i Stängda Skolplattformen så att man gör likadant.
