### ISSUE TITLE
Önskemål: Lägg till möjlighet att dölja bilder i nyhetsbrev

### ISSUE THREAD

**Issue by peterk** [kolplattformen/skolplattformen#76]
The newsletter functionality is already better than in the original version. But a lot of screen space is occupied with a picture with no relevant information. It would be great if it could be removed entirely or via a setting (I went through as many newsletters I could find and none of them contain meaningful information.). See examples below.

![image](https://user-images.githubusercontent.com/19284/107741946-708a1780-6d0e-11eb-9182-d4e3f180007c.png)
![image](https://user-images.githubusercontent.com/19284/107741976-7ed83380-6d0e-11eb-8da3-114ff4ddd93f.png)

**Comment by JohanObrink** [comment]
@peterk Jag ändrade rubriken i din issue. Vi bestämde oss just för att gå över till svenska och försöka få till CD med Semantic releases. Hoppas jag översatte korrekt 😄

**Comment by peterk** [comment]
Det låter toppen.

**Comment by believer** [comment]
@peterk jag öppnade #164 där bilden flyttas ner efter textinnehållet och även lite andra stylingjusteringar för nyheterna. Funkar det bra som en första lösning?
