### ISSUE TITLE
Annat barns nyheter

### ISSUE THREAD

**Issue by piaullstrom** [kolplattformen/skolplattformen#77]
Jag har 2 ungar på samma förskola men i olika grupper. Får upp äldre ungens ”nyheter” även på yngsta trots att det ska vara olika. På Skolplattformen får jag upp rätt just idag men jag är ganska säker på att jag haft samma problem där.

**Comment by JohanObrink** [comment]
@piaullstrom  Oj... den var lurig 🤔 Vi släpper en uppdatering i dagarna som fixar en bugg vid ut- och inloggning men den borde inte påverka det problemet.

Just att växla mellan barn har vi testat rätt noggrant så det borde inte vara där felet ligger. Men buggar beter sig sällan som de borde.

Kan vi återkomma till buggen efter nästa uppdatering och se om det löser sig med den så får vi försöka lista ut hur vi ska kunna återskapa felet?

**Comment by Cathmelar** [comment]
Upplever samma problem. Nyheter som gäller barnet med förnamn på A syns istället för S' nyheter.

**Comment by piaullstrom** [comment]
Slänger upp lite skärmdumpar. Barnet som slutar på -a får nyheterna på barnet som sluter på -e. 
![E4521C8E-C6DE-49F6-86B3-9C39FD077210](https://user-images.githubusercontent.com/78951134/107753914-0b8bed00-6d21-11eb-9f19-7b288aa48328.jpeg)
![7A408569-5BED-4ABB-B113-75A00D35349C](https://user-images.githubusercontent.com/78951134/107753917-0cbd1a00-6d21-11eb-8a04-42ed09b49a0c.jpeg)
![6282FF2F-2BEB-46A1-BB6A-3014D234FD17](https://user-images.githubusercontent.com/78951134/107753919-0d55b080-6d21-11eb-9126-4ce93ef1ea7b.jpeg)
![07F0C004-2019-4174-AA88-01917E31EE2E](https://user-images.githubusercontent.com/78951134/107753922-0dee4700-6d21-11eb-9853-95d93f51cbb4.jpeg)

**Comment by piaullstrom** [comment]
Funkar just nu så ett varierande problem

**Comment by irony** [comment]
@JohanObrink - kan det vara den cache-key som vi använder inte är olika på alla skolor?

**Comment by JohanObrink** [comment]
@irony Jaa... det blir i så fall samma item i redux storen så då ballar det ju ur. Men det är en GUID. Hur skulle de råka ha samma GUID? Eller minns jag fel?

**Comment by andersjaensson** [comment]
Jag har samma problem, och det gäller inte bara `Nyheter` utan även `Kalender`. Däremot verkar `Klassen` inte ha samma problem.

**Comment by JohanObrink** [comment]
@irony Der där är ju nyhetslistan - inte detaljsidan. Den nycklas på `child.id`. De borde väl ändå inte kunna vara samma? Jag måste ha korsat några kablar någonstans. Och jag kan inte återskapa det för jag har bara _ett_ barn i Srockholmsskola. Du får nog hjälpa mig.

**Comment by jooon** [comment]
Har samma problem. Två barn, förskola och förskoleklass. I vyn Dina barn visas alltid det yngre barnet i förskola överst. Det äldre barnet i förskoleklass visas längst ned.

När jag går in på yngre barnet så visas ALLTID rätt nyheter för det barnet.

Ofta, men inte alltid, när jag går in på äldre barnet efter att ha loggat in så visas det yngre barnets nyheter. Ibland visas rätt nyheter. I samma session så visas alltid samma nyheter hur jag än bläddrar fram och tillbaka. Endast om jag stänger appen eller loggar ut utan att stänga appen och sen loggar in igen har jag lyckats få den att byta nyheter.

Upplevde inte problemet i 1.0.0, bara i 1.1.0 och 1.1.1 på Android. Kanske bara var slumpen. Jag hann nog inte använda 1.0.0 mycket.

Kan även tillägga att det inte bara är Nyheter som är fel för mig. Kalendern på det äldre barnet är ibland tom. Oklart om det är samma bug, för det yngre barnets kalender är alltid tom. Vad som visas i Kalendern kan vara oberoende av vad som visas på Nyheter. Har sett rätt/fel Nyheter och tom kalender. Vet ej om jag sett kombinationen rätt Kalender och fel Nyheter.

Aviseringar och Klassen verkar alltid vara rätt.

**Comment by andersjaensson** [comment]
Jag har fortfarande det här problemet på android, v1.3.0. Borde det vara löst där? 
För mig gör det här att appen tyvärr är helt oanvändbar.. Jag är kass på javascript men hjälper gärna till med testning eller annat @JohanObrink

**Comment by andersjaensson** [comment]
Ah, nu såg jag https://github.com/kolplattformen/skolplattformen/issues/132
