### ISSUE TITLE
BankID-knapp döljs vid inloggning

### ISSUE THREAD

**Issue by AsaPlesner** [kolplattformen/skolplattformen#78]
När jag loggar in (på en iPhone 7) ligger siffermenyn kvar när jag har matat in mitt personnummer. Den döljer det mesta av den knapp som öppnar BankID-appen och det gör det lite bökigt och otydligt hur jag ska komma vidare.

 
![IMG_2694](https://user-images.githubusercontent.com/78957420/107756169-21e77800-6d24-11eb-9253-fcd992080099.PNG)

**Comment by ErikHellman** [comment]
Tack! Vi har en fix på detta som vi hoppas vi kan få ut så snart som möjligt!

**Comment by JohanObrink** [comment]
@AsaPlesner Tack för din issue 👍🏻 

Detta är löst i v1.1.0
