### ISSUE TITLE
Dina barn står bara och laddar...

### ISSUE THREAD

**Issue by johanlindfors** [kolplattformen/skolplattformen#81]
Det kan vara så att mina barn inte ska synas i Skolplattformen, men upplevelsen är fortfarande att efter att jag loggat in med BankId så står vyn "Dina barn" och "Laddar..." och hjulet snurrar... Kommer inte vidare och får inget meddelande!

**Comment by irony** [comment]
Tack! Ja vi har inte lagt in något bra stöd för fallet då man inte har några barn i skolplattformen. Hög prio. Tack!

**Comment by MirjamMirre** [comment]
Kan vara samma bugg... har loggat in, och dirigeras till fliken Dina barn där det är stopp. Bifogar iPhone screen dumpar.

![E06FDEF0-458D-49E5-811A-4B4CF3CBFB84](https://user-images.githubusercontent.com/78966012/107775672-e3ac8180-6d40-11eb-8e49-03d53aa4fc13.png)
![DA86160B-2F4B-438F-8BE5-DF3371C7016B](https://user-images.githubusercontent.com/78966012/107775680-e6a77200-6d40-11eb-8748-dcb92bfa2b4f.png)

**Comment by piaullstrom** [comment]
Jag skriver in personnummer (utan 19), då fyller den på och går vidare (utan att jag trycker på något) till ”dina barn” och står där och laddar. Om jag backar och trycker på bank-Id kommer jag till bank-id identifiering och sen kommer jag in.

**Comment by alsmyr** [comment]
> Kan vara samma bugg... har loggat in, och dirigeras till fliken Dina barn där det är stopp. Bifogar iPhone screen dumpar.
> 
@MirjamMirre, jag skulle ta bort personnumret ditt från bilden om jag vore dig. Trevlig helg!

**Comment by MirjamMirre** [comment]
Tack Alsmyr för påminnelsen 🙏🏼

**Comment by believer** [comment]
Jag lade in en vy i #126 när användaren inte har några barn i Stockholms Stad. Löser det kanske problemet?

**Comment by johanlindfors** [comment]
Fungerar lysande, nu vet jag åtminstone att jag inte kan använda appen :)
