### ISSUE TITLE
Kom ihåg personnummer

### ISSUE THREAD

**Issue by andlju** [kolplattformen/skolplattformen#82]
Det skulle vara skönt att inte behöva skriva in sitt personnummer varje gång man öppnar appen. Kan man lagra det lokalt? Kanske en "Kom ihåg mig"-switch för säkerhets skull?

**Comment by irony** [comment]
Den ska spara automatiskt när du skriver ett giltigt personnr. Vill du dubbelkolla? Och om det inte fungerar får du gärna PM:a ditt personnr så kan vi se om det är en bugg i personnr valideringen?

**Comment by andlju** [comment]
Själva valideringen verkar fungera - för om jag skriver en siffra fel så blir bankid-knappen grå.

Ser nu att om jag aktivt loggar ut så står personnr kvar, men om jag forcerar en stängning av appen så är det borta nästa gång jag öppnar den. Är osäker på om det kanske var det jag gjorde första gången också - kan ha varit så.

**Comment by andlju** [comment]
Just det, en iPhone XS är det jag har förresten. Kanske kan vara relevant info tänker jag. :)

**Comment by jooon** [comment]
Har samma problem i Android-versionen. 1.0.0, 1.1.0 och 1.1.1. Google Pixel 2 XL. Android 11.

**Comment by zhouhana** [comment]
Jag använder iPhone SE och har samma problem. PM:ar mitt personnummer.

**Comment by jooon** [comment]
Gäller även för testanvändaren med personnumret 1212121212, så det har nog inget med personnumret i sig att göra.

**Comment by zhouhana** [comment]
Det finns väl ingen risk att man måste ta bort denna "badge" om detta implementeras? Om det finns risk att sparandet av personnummer gör att staden drar öronen åt sig det minsta när det gäller att tillåta den här appen att vara kvar så tycker jag att det är onödigt att implementera detta. Det finns mycket annat att förbättra avseende inloggningsförfarandet.

![image](https://user-images.githubusercontent.com/493629/107856172-c18d2f00-6e26-11eb-807f-e27911c74ff4.png)
