### ISSUE TITLE
Hoppa automatiskt tillbaka till appen efter BankID-inlogg

### ISSUE THREAD

**Issue by andlju** [kolplattformen/skolplattformen#83]
Gissar att det har att göra med vad man använder för SDK eller så för BankID? Det är ju trevligt om man inte själv behöver hoppa tillbaka till appen efter inloggning (vilket jag nu behöver göra på min iPhone XS i alla fall).

**Comment by johanlindfors** [comment]
Jag hade samma "problem" men trodde att det hade att göra med att jag loggade in i BankId på en separat enhet och inte på min iOS enhet.

**Comment by irony** [comment]
Tyvärr går det inte. Det är bara appen som är officiellt knuten till BankID som kan få en url tillbaka från BankID appen.
