### ISSUE TITLE
Android app icon is incorrect

### ISSUE THREAD

**Issue by devilbuddy** [kolplattformen/skolplattformen#89]
Downloaded from Play Store (v 1.1.0) - App icon is incorrect

![image](https://user-images.githubusercontent.com/1422331/107844605-1e5ff980-6dd5-11eb-916d-381791dfe9fd.png)

**Comment by devilbuddy** [comment]
Display name specified here:

https://github.com/kolplattformen/skolplattformen/blob/main/packages/app/android/app/src/main/res/values/strings.xml

**Comment by rotsee** [comment]
![screenshot from home screen](https://user-images.githubusercontent.com/122874/107848467-f764f000-6df3-11eb-9495-298cfb510a80.jpg)

Screenshot from home screen

**Comment by JohanObrink** [comment]
@devilbuddy Tack för din issue 👍🏻 

Detta ska vara löst i v1.1.1
