### ISSUE TITLE
Nyhetssida med inbäddad fil fungerar inte 

### ISSUE THREAD

**Issue by elektromin** [kolplattformen/skolplattformen#90]
Här kommer skärmbilder från samma nyhet på öppna Skolplattformen jämfört med den vanliga appen. Nyheten innehåller ett inbäddat dokument som inte kan visas. 

![50F09F24-622C-48A9-9FB4-788DFEAABA63](https://user-images.githubusercontent.com/5320323/107844776-c1fdd980-6dd6-11eb-8e1a-2a2ee2554295.png)
![4BB55CF6-CAD4-4D72-9A9C-1CFCC66701E0](https://user-images.githubusercontent.com/5320323/107844779-c4603380-6dd6-11eb-9889-f640286d19ed.png)

**Comment by Eorlingur** [comment]
Jag tror detta är samma som #13

**Comment by kajetan-kazimierczak** [comment]
Verkar vara problem med inbäddade bilder också (huvudbilden fungerar).

Jag har källan till en sån ickefungerande nyhet i json sparat från fiddler. Delar gärna med mig av den, men inte publikt, då det trots allt är en nyhet som inte är avsedd att bara publik. Vem kan jag skicka den till?

**Comment by JohanObrink** [comment]
Fixat i v1.2.0 (iOS) resp. v1.3.0 (Android)
