### ISSUE TITLE
Lägg till kalenderhändelser i mobilens egna kalender

### ISSUE THREAD

**Issue by ppswede** [kolplattformen/skolplattformen#93]
Feature request: Kunna antingen a) synka kalenderhändelser för samtliga barn direkt in i mobilens kalender (så att t.ex. APT, studiedagar automatiskt finns i egen kalender när de läggs in) eller b) kunna trycka på en kalenderhändelse för att lägga till den i mobilens egna kalender från listan.

**Comment by believer** [comment]
Ditt fall **B** har lagts till i #165 🎉
