### ISSUE TITLE
Inloggningsförbättringar

### ISSUE THREAD

**Issue by zhouhana** [kolplattformen/skolplattformen#94]
Så här ser det ut när jag loggar in i appen på min första generationens iPhone SE:

![bankid_skolplattformen](https://user-images.githubusercontent.com/493629/107851834-060bd100-6e0d-11eb-930a-55a42487658e.png)

1. Jag möts av en blaffa siffror och vet inte vad jag ska göra. Det känns inte ens som att jag är i en app eftersom klockan och symbolerna i skärmens överkant är borta. (Egentligen är de där fast i vitt mot vitt. Jag har lagt in en separat issue om detta: #103) Men okej, jag testar väl att fylla i mitt personnumer.
2. När jag skrivit i sista siffran händer något bakom bilden. Jag funderar på hur jag ska kunna stänga ner blaffan (jag ser att det finns en issue inlagd om att den inte stängs: #78) och trycker till slut på bilden ovanför.
3. Bilden är dock länkad till sidan "Dina barn". Varför är den det? Jag backar tillbaka.
4. Nu ser det tydligare ut. Jag trycker på "Öppna BankID".
5. Jag fyller i min BankID-kod.
6. Jag trycker på "Identifiera".
7. I det sista steget måste jag manuellt byta tillbaka till Skolplattformen-appen.

Egentligen borde man inte behöva fylla i personnumret alls, och även bli automatiskt tillbakaskickad till Skolplattformen-appen, som hos Kivra och de flesta banker:

![bankid_kivra](https://user-images.githubusercontent.com/493629/107852023-7109d780-6e0e-11eb-9978-a9bd26487a5d.png)

1. Jag trycker på "Logga in".
2. Jag fyller i min BankID-kod.
3. Jag trycker på "Identifiera".

Eventuellt skulle man kunna visa de fyra första sex siffrorna, som hos Klarna när man loggar in efter första gången, men det känns onödigt. Man ser i BankID-appen vem man försöker logga in som.

![bankid_klarna_2](https://user-images.githubusercontent.com/493629/107852073-d231ab00-6e0e-11eb-95ce-a877817a7ecd.png)

Så här ser det ut i Klarna-appen första gången man loggar in. Notera skärm 2 och 3 där man har möjlighet att spara personnumret (jag ser att det finns en annan issue inlagd om att spara personnummer: #82 – dock, personnummer är ju den ultimata personuppgiften och om sparandet av den på något sätt grumlar chanserna till att staden låter den här appen finnas kvar så tycker jag man klarar sig om bara inloggningsförfarandet blir lika smidigt som i skärm 2) och tydligt ser inloggningsknappen även när sifferblaffan täcker skärmen. Ligger dessa två steg hos BankID? I så fall kanske ni kan "låna" dessa steg relativt enkelt? Eller är det i så fall Stockholms stad som måste göra det?

![bankid_klarna_1](https://user-images.githubusercontent.com/493629/107852177-964b1580-6e0f-11eb-8faa-4639bc1debbe.png)

Det vore trevligt också om BankID-loggan fanns på knappen. Då fattar hjärnan direkt vad som gäller. Hursomhelst säger mig symbolen med nio cirklar ingenting i detta fall.

Det är onödigt att inloggningsknappen är utgråad så länge personnumret inte är ifyllt. Ingen annan BankID-implementation som jag sett villkorar inloggningsknappen. Villkorsfunktioner och funktioner som "hjälper" användaren till rätt format ökar risken för buggar och krångel både för utvecklarna och användarna. Den uppfattas dessutom mycket lättare som en knapp när den är rosa.

![bankid_skolplattformen_0](https://user-images.githubusercontent.com/493629/107852549-99470580-6e11-11eb-87bf-bcc42e2896f5.png)

Till sist: Informationen om antalet siffror i personnummerfältet är för lång för att rymmas i fältet. *Om* användaren nu ska fylla i sitt personnummer och *om* appen då ska instruera användaren om antalet siffror så tycker jag att det är bättre att ge enbart *ett* alternativ, nämligen det enklaste, som är tio siffror, och att ge alternativet som ett exempel: "ÅÅMMDDXXXX". Om användaren då skriver in tolv siffror så kan systemet ignorera de två första, men om användaren skriver in tio siffror och systemet förväntar sig tolv så vet inte systemet vilka två siffror som ska läggas till eller var de ska läggas till.

**Comment by zhouhana** [comment]
I övrigt, TACK för denna app! Verkligen behövd.

**Comment by JohanObrink** [comment]
@zhouhana Hej! De första punkterna löstes iom v1.1.0

Att växla tillbaka till appen verkar just nu omöjligt iom att vi piggy-backar på Skolpplattformens identifiering.

Att köra utan personnummer är något vi kollar på. Får se om det går att lösa iom piggyback.
