### ISSUE TITLE
Elevdokumentation, inloggning BankID not working 

### ISSUE THREAD

**Issue by ps-contributor** [kolplattformen/skolplattformen#96]
BankID doesnt respond in automatic or manual mode. 
![F792540D-40F8-4EE9-9F2F-502348F5BD89](https://user-images.githubusercontent.com/79000290/107846508-9550be80-6de4-11eb-8380-3006cf36fada.png)

**Comment by kajetan-kazimierczak** [comment]
För iOS är detta fixat, för Android är det nog samma underliggande fel som https://github.com/kolplattformen/skolplattformen/issues/370
