### ISSUE TITLE
Some string missing in "aviseringar" 

### ISSUE THREAD

**Issue by rotsee** [kolplattformen/skolplattformen#99]
![Screenshot_20210213_120357_org skolplattformen app](https://user-images.githubusercontent.com/122874/107848520-5460a600-6df4-11eb-90ef-ef0a411b37d2.jpg)
There is an empty parenthesis after each item in the aviseringar view, making me believe something might be missing there?

**Comment by jooon** [comment]
I have the same problem. If I login with 1212121212 and check the test data it looks like it should be a relative date like (2 months ago).

Hej Leo! :)

**Comment by rotsee** [comment]
:wave: @jooon! :)

**Comment by JohanObrink** [comment]
Hej @rotsee !

Tack för din issue 👍🏻 

Skulle du kunna hjälpa oss lite med felsökningen? Öppna nätverksfliken i Chrome tools och gå till Skolplattformen på webben.

Leta upp anropet till https://etjanst.stockholm.se/vardnadshavare/inloggad2/Overview/GetNotification?childId= osv... och klicka på det.

Kopiera innehållet i Response och klistra in i valfri editor. Rensa bort/ersätt all personlig information (inkl. GUID:ar, userId och sånt) och klistra in här.

**Comment by rotsee** [comment]
Så här ser ett meddelande ut (datumformat etc verkar lika i alla meddelanden). Sedan innehåller `Message` i sin tur en json-blob som textsträng. Säg till om du vill se den också!

```
{
  "Notification": {
    "Messageid": "...",
    "Messagecorrelationid": "...",
    "Message": "...",
    "Readreceipt": false,
    "Recipient": "...",
    "Id": ...,
    "DateCreated": "2021-02-02T15:39:51.723",
    "DateModified": "/Date(1612280391723)/",
    "Role": "Guardian",
    "Participant": "..."
  },
  "NotificationMessage": {
    "Messages": {
      "Message": {
        "Messageid": "...",
        "Messagecorrelationid": "...",
        "Messagetext": "Nu kan du ta del av ditt barns dokumentation av utvecklingssamtal",
        "Messagetime": "/Date(1612276490126)/",
        "Linkbackurl": "...",
        "Category": null,
        "Sender": {
          "Name": "Elevdokumentation"
        },
        "Recipient": {
          "RecipientRecipient": "...",
          "Role": "Guardian",
          "Schooltype": null
        },
        "Messagetype": {
          "Type": "webnotify"
        },
        "System": "Elevdokumentation"
      }
    }
  }
}
```

**Comment by jooon** [comment]
Har samma struktur på mina aviseringar. Rensar ut potentiellt känsligt men sparar Message med json i json som innehåller en timestamp med tidszon.

```
{
  "Notification": {
    "DateCreated": "2021-02-12T12:42:46.477",
    "DateModified": "/Date(1613133766477)/",
    "Id": 1234567,
    "Message": "{\"messages\":{\"message\":{\"messageid\":\"...\",\"messagecorrelationid\":\"...\",\"messagetext\":\"Ett nytt inlägg i en lärlogg har skapats.\",\"messagetime\":\"2021-02-12T11:42Z\",\"linkbackurl\":\"https://start.unikum.net/SP/Login?entityID=...\",\"category\":\"Lärlogg\",\"sender\":{\"name\":\"Planering och Bedömning\"},\"recipient\":{\"recipient\":\"...\",\"role\":\"Guardian\",\"schooltype\":\"FS\"},\"messagetype\":{\"type\":\"avisering\"},\"system\":\"Planering och Bedömning\",\"participant\":\"...\"}}}",
    "Messagecorrelationid": "...",
    "Messageid": "...",
    "Participant": "...",
    "Readreceipt": false,
    "Recipient": "...",
    "Role": "Guardian"
  },
  "NotificationMessage": {
    "Messages": {
      "Message": {
        "Category": "Lärlogg",
        "Linkbackurl": "https://start.unikum.net/SP/Login?entityID=...",
        "Messagecorrelationid": "...",
        "Messageid": "...",
        "Messagetext": "Ett nytt inlägg i en lärlogg har skapats.",
        "Messagetime": "/Date(1613130120000)/",
        "Messagetype": {
          "Type": "avisering"
        },
        "Recipient": {
          "RecipientRecipient": "personnummer",
          "Role": "Guardian",
          "Schooltype": "FS"
        },
        "Sender": {
          "Name": "Planering och Bedömning"
        },
        "System": "Planering och Bedömning"
      }
    }
  }
}
```

Gillar att vi har tider att välja på.

"DateCreated": "2021-02-12T12:42:46.477"
"DateModified": "/Date(1613133766477)/"
"messagetime": "2021-02-12T11:42Z"
"Messagetime": "/Date(1613130120000)/"

Får inte riktigt ihop tidszonen heller. Om 11:42Z stämmer så är ju 12:42:46.477 CET men då kan ju inte 1613133766477 vara millisekunder sedan 1970-01-01 00:00 UTC utan måste vara CET.
